### ISSUE TITLE
Native Webhook updates all helm releases even if keel isn't enabled

### ISSUE THREAD

**Issue by htplbc** [keel-hq/keel#109]
I currently have 3 namespaces for the an app - dev, qa, prod

I have enabled keel on the dev namespace via helm. When I went to POST a native webhook payload to keel it found that the qa and prod helm-releases matched

```
time="2017-10-12T07:40:09Z" level=info msg="provider.kubernetes: processing event" registry= repository=docker.artifactory.XXXXXX.com/user/test-proj tag=1.0-SNAPSHOT-develop
time="2017-10-12T07:40:09Z" level=info msg="provider.helm: processing event" registry= repository=docker.artifactory.XXXXXX.com/user/test-proj tag=1.0-SNAPSHOT-develop
time="2017-10-12T07:40:09Z" level=info msg="provider.kubernetes: no plans for deployment updates found for this event" image=docker.artifactory.XXXXXX.com/user/test-proj tag=1.0-SNAPSHOT-develop
time="2017-10-12T07:40:10Z" level=info msg="provider.helm: impacted release container found" parsed_image="docker.artifactory.XXXXXX.com/user/test-proj:1.0-SNAPSHOT-develop" policy=force target_image=docker.artifactory.XXXXXX.com/user/test-proj target_image_tag=1.0-SNAPSHOT-develop
time="2017-10-12T07:40:10Z" level=info msg="provider.helm: impacted release container found" parsed_image="docker.artifactory.XXXXXX.com/user/test-proj:1.0-RC2-release-1.0" policy=force target_image=docker.artifactory.XXXXXX.com/user/test-proj target_image_tag=1.0-SNAPSHOT-develop
time="2017-10-12T07:40:10Z" level=info msg="provider.helm: impacted release container found" parsed_image="docker.artifactory.XXXXXX.com/user/test-proj:1.0-RC2-release-1.0" policy=force target_image=docker.artifactory.XXXXXX.com/user/test-proj target_image_tag=1.0-SNAPSHOT-develop
time="2017-10-12T07:40:10Z" level=info msg="provider.helm: images do not match, ignoring" parsed_image_name="index.docker.io/karolisr/keel:0.5.0-rc.1" target_image_name=docker.artifactory.XXXXXX.com/user/test-proj
time="2017-10-12T07:40:13Z" level=info msg="provider.helm: release updated" release=project-dev version=8
time="2017-10-12T07:40:16Z" level=info msg="provider.helm: release updated" release=project-qa version=3
time="2017-10-12T07:40:19Z" level=info msg="provider.helm: release updated" release=project-prod version=3
```

**Comment by rusenask** [comment]
Hey @htplbc, thanks for bringing this up, will take a look. Could you please provide a sample deployment.yml template of your helm chart? It should only process charts that have keel config provided in values.yml.

**Comment by htplbc** [comment]
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Chart.Name }}
        release: {{ .Release.Name }}
      name: {{ .Chart.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
    spec:
      containers:
      - env:
        - name: server_port
          value: {{int .Values.server_port |quote}}
        - name: cookieSecure
          value: {{ .Values.cookieSecure | quote }}
        - name: cookieDomain
          value: {{ .Values.stackDomain | quote }}
        - name: cookieMaxAgeSec
          value: {{int .Values.cookieMaxAgeSec | quote }}
        - name: authCookieName
          value: {{ .Values.authCookieName | quote }}
        - name: envCookieName
          value: {{ .Values.envCookieName | quote }}
        - name: bootCookieName
          value: {{ .Values.bootCookieName | quote }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        ports:
        - containerPort: 9000
          protocol: TCP
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "2"
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: {{ .Values.image.repoSecretName }}
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
```
