### ISSUE TITLE
only picking up 1 trigger.poll.WatchTagJob

### ISSUE THREAD

**Issue by hexsprite** [keel-hq/keel#166]
I've defined 3 deployments, two of which use a `:stable` tag and one which uses a `:master` tag.

Expected: Both tagged images will be watched for changes
Actual: only the 1st (`:stable`) is watched

Despite the fact that all 3 deployments have the same keel-related labels and annotations the one using the image with the :master tag is not listed

Indeed if I grep `master` there's nothing in the logs.

When keel starts up I see:

```
time="2018-03-19T01:14:13Z" level=debug msg="trigger.poll.WatchTagJob: checking digest" current_digest="sha256:32c5881b15eba75b6ae39e2b8a3be38890870bbb9922bdbd1d03e4c808a0f558" image_name="index.docker.io/hexsprite/focuster:stable" new_digest="sha256:32c5881b15eba75b6ae39e2b8a3be38890870bbb9922bdbd1d03e4c808a0f558"
```

These are the annotations used in all 3 deployments.

```
  labels:
    keel.sh/policy: force
    keel.sh/trigger: poll      
  annotations:
    keel.sh/pollSchedule: "@every 30s"
```

Anything I could be doing wrong?
