### ISSUE TITLE
memory usage goes up rapidly

### ISSUE THREAD

**Issue by hexsprite** [keel-hq/keel#171]
Memory goes up until the node gets evicted due to memory usage.

Not sure if this is related to the latest update.

![image](https://user-images.githubusercontent.com/23538/38062143-395ec11a-32a7-11e8-850a-62a6c46d9066.png)

**Comment by rusenask** [comment]
Hi, could you please provide some more info:

* what triggers do you use? poll?
* which provider or both?

Anything suspicious in the logs?

**Comment by hexsprite** [comment]
I'm using the K8s provider. 

```
# frontend.yaml
...
metadata:
  name: frontend
  labels:
    keel.sh/policy: force
    keel.sh/trigger: poll      
  annotations:
    keel.sh/pollSchedule: "@every 30s"
...
        image: xxx:stable
```

I also have a second deployment that uses the identical settings, same image.  Then I have a 3rd deployment that uses a different image using the `:master` tag.
