### ISSUE TITLE
Pre-release tag with force policy updates everything

### ISSUE THREAD

**Issue by azr** [keel-hq/keel#187]
Howdy

I have a deployment with:
```
...
  labels:
    version: staging
    keel.sh/policy: force 
    keel.sh/approvals: "0"
...
      containers:
      - name: bar
        image: eu.gcr.io/foo/bar:latest-staging
```

But if I tag the same docker image 3 times (sha, branch-name & pre-release tag) and push, keel triggers 3 deploys, which shows 3 notifications:

![screen shot 2018-04-09 at 3 59 44 pm](https://user-images.githubusercontent.com/1024852/38502204-1c6c86c0-3c0f-11e8-81b3-bcea4d533cd4.png)

I think it would be better if keel.sh could match the prerelease tag in there, do you agree ?

I can help do this too !! 😄 

Also as a side question : since they are the same image & have the same digest, shouldn't a deploy get triggered only once here ?
