### ISSUE TITLE
Keel with sub-chart / umbrella app

### ISSUE THREAD

**Issue by svnlto** [keel-hq/keel#188]
Hey, I thought I'd ask before I run into a scenario where this isn't supposed to work anyway.

I have 1 main chart that spins up several others. The helm examples here only show how to use keel with a single stand-alone chart. How would you go about setting this up in the sub-charts scenario?
Would I add keel to my sub-charts or can the "main" chart be used?

Let's say I have the two images below as part of my chart.

```yaml
images:
    - repository: redis.image.repository 
      tag: redis.image.tag 
    - repository: elasticsearch.image.repository 
      tag:  elasticsearch.image.tag 
```

If I understood the docs, this should be a valid configuration.

**Comment by rusenask** [comment]
Hi, I wonder how Helm works with these multiple charts, does it combine values.yaml? Maybe @rimusz  knows? 

If it does combine, then you only need to define keel config in the main chart. If it doesn't combine them, then it should go into the sub-charts.

This

```
images:
    - repository: redis.image.repository 
    - tag: redis.image.tag 
```

Would just tell Keel that there is an image variable located in values.yaml

```
redis:
  image:
    repository: some/image
    tag: sometag
```

It uses parsers from Helm to get those variables, so as long as Helm can get that template info then Keel will get it too. From this it seems that the correct approach would be to specify config in sub-charts since multiple charts wouldn't be able to share same values.yaml (I might be wrong as I haven't used helm in this way).

**Comment by svnlto** [comment]
```yaml
images:
    - repository: redis.image.repository 
      tag: redis.image.tag 
    - repository: elasticsearch.image.repository 
      tag:  elasticsearch.image.tag 
```
This works just fine.
