### ISSUE TITLE
Google Container Registry error

### ISSUE THREAD

**Issue by codebreach** [keel-hq/keel#194]
When polling on an image deployed from GCP, I get the following error and am unable to move forward.

The image is deployed with a pull secret using a service account. This service account has project viewer access as mentioned here: https://stackoverflow.com/questions/44783736/how-to-list-images-and-tags-from-the-gcr-io-docker-registry-using-the-http-api

```
time="2018-04-18T11:19:18Z" level=error msg="trigger.poll.manager: failed to start watching repository" error="Get https://gcr.io/v2/ZZZZZZ-177614/sd/django-rest-api/manifests/master: http: non-successful response (status=401 body=\"{\\\"errors\\\":[{\\\"code\\\":\\\"UNAUTHORIZED\\\",\\\"message\\\":\\\"Requested repository does not match bearer token resource: ZZZZZZ-177614/sd/django-rest-api\\\"}]}\")" image="gcr.io/ZZZZZZZ-177614/sd/django-rest-api:master" schedule="@every 5m"
```

**Comment by rusenask** [comment]
Hi, you don't need polling trigger for images in the GCR, it should use pubsub trigger https://keel.sh/v1/guide/documentation.html#Google-Cloud-GCR-registry. With pubsub updates are instant :)

**Comment by codebreach** [comment]
OK I was working on that but since I have a running cluster, adding new pools is task...

Question on that - can just the Node running the keel pod(s) have the required permission? (auth/pubsub)

**Comment by rusenask** [comment]
I think it can if you follow this guide https://cloud.google.com/kubernetes-engine/docs/tutorials/authenticating-to-cloud-platform, google's pubsub library will respect GOOGLE_APPLICATION_CREDENTIALS env variable. 

I tried it once but with storage buckets on another project, it was complaining about permissions (although authentication passed).

**Comment by codebreach** [comment]
The permissions seem to be OK but I dont think its working.

This is the last log message I see:
```
time="2018-04-18T14:26:13Z" level=info msg="trigger.pubsub: subscribing for events..." subscription=REDACTED
```

also is there a way to increase log level (to debug)?

**Comment by rusenask** [comment]
Yes, you can set env variable DEBUG="1" or any string, as long as it's not empty. Regarding pubsub, please check in your google cloud console under Pub/Sub whether there are any subscriptions.

**Comment by codebreach** [comment]
OK Pub/Sub is not the issue. 

Now I am getting some weird log message:
`no plans for deployment updates found for this event`

Following is the values.yaml
```yaml

#auto deploys
keel:
  # keel policy (all/major/minor/patch/force)
  policy: force
  # trigger type, defaults to events such as pubsub, webhooks
  # trigger: pubsub
  # images to track and update
  images:
    - repository: image.repository
      tag: image.tag
```

Log:
```

keel | Apr 18, 2018, 11:29:21 PM | time="2018-04-18T17:59:21Z" level=info msg="provider.kubernetes: no plans for deployment updates found for this event" image=gcr.io/ZZZZZZZZ-177614/sd/django-rest-api tag=master
keel | Apr 18, 2018, 11:29:20 PM | time="2018-04-18T17:59:20Z" level=error msg="provider.helm: failed to parse version" error="invalid semantic version" tag=master
keel | Apr 18, 2018, 11:29:20 PM | time="2018-04-18T17:59:20Z" level=error msg="provider.helm: failed to parse version" error="invalid semantic version" tag=master
keel | Apr 18, 2018, 11:29:20 PM | time="2018-04-18T17:59:20Z" level=error msg="provider.helm: failed to parse version" error="invalid semantic version" tag=master
keel | Apr 18, 2018, 11:29:20 PM | time="2018-04-18T17:59:20Z" level=error msg="provider.helm: failed to parse version" error="invalid semantic version" tag=master
keel | Apr 18, 2018, 11:29:20 PM | time="2018-04-18T17:59:20Z" level=error msg="provider.helm: failed to parse version" error="invalid semantic version" tag=master
keel | Apr 18, 2018, 11:29:20 PM | time="2018-04-18T17:59:20Z" level=error msg="provider.helm: failed to parse version" error="invalid semantic version" tag=master
keel | Apr 18, 2018, 11:29:20 PM | time="2018-04-18T17:59:20Z" level=error msg="provider.helm: failed to parse version" error="invalid semantic version" tag=master
keel | Apr 18, 2018, 11:29:20 PM | time="2018-04-18T17:59:20Z" level=error msg="provider.helm: failed to parse version" error="invalid semantic version" tag=master
keel | Apr 18, 2018, 11:29:20 PM | time="2018-04-18T17:59:20Z" level=error msg="provider.helm: failed to parse version" error="invalid semantic version" tag=master
keel | Apr 18, 2018, 11:29:20 PM | time="2018-04-18T17:59:20Z" level=error msg="provider.helm: failed to parse version" error="invalid semantic version" tag=master
keel | Apr 18, 2018, 11:29:20 PM | time="2018-04-18T17:59:20Z" level=error msg="provider.helm: failed to parse version" error="invalid semantic version" tag=master
keel | Apr 18, 2018, 11:29:20 PM | time="2018-04-18T17:59:20Z" level=error msg="provider.helm: failed to parse version" error="invalid semantic version" tag=master
keel | Apr 18, 2018, 11:29:20 PM | time="2018-04-18T17:59:20Z" level=error msg="provider.helm: failed to parse version" error="invalid semantic version" tag=master
keel | Apr 18, 2018, 11:29:20 PM | time="2018-04-18T17:59:20Z" level=error msg="provider.helm: failed to parse version" error="invalid semantic version" tag=master
keel | Apr 18, 2018, 11:29:20 PM | time="2018-04-18T17:59:20Z" level=error msg="provider.helm: failed to parse version" error="invalid semantic version" tag=master
keel | Apr 18, 2018, 11:29:20 PM | time="2018-04-18T17:59:20Z" level=error msg="provider.helm: failed to parse version" error="invalid semantic version" tag=master
keel | Apr 18, 2018, 11:29:20 PM | time="2018-04-18T17:59:20Z" level=error msg="provider.helm: failed to parse version" error="invalid semantic version" tag=master
keel | Apr 18, 2018, 11:29:20 PM | time="2018-04-18T17:59:20Z" level=info msg="provider.kubernetes: processing event" registry= repository=gcr.io/ZZZZZZZZ-177614/sd/django-rest-api tag=master
keel | Apr 18, 2018, 11:29:20 PM | time="2018-04-18T17:59:20Z" level=info msg="provider.helm: processing event" registry= repository=gcr.io/ZZZZZZZZ-177614/sd/django-rest-api tag=master
keel | Apr 18, 2018, 11:29:20 PM | time="2018-04-18T17:59:20Z" level=debug msg="trigger.pubsub: got message" action=INSERT image_name="ZZZZZZZZ-177614/sd/django-rest-api:master" tag=master


```

**Comment by codebreach** [comment]
thanks so much for helping me out with this...
I have tried putting date/deploy-date into the annotations of the template but its the same...

```yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    track: {{ .Values.track }}
    tier: app
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 7
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        release: {{ .Release.Name }}
        track: {{ .Values.track }}
        tier: app
      annotations:
        date/deploy-date: {{ now | quote }}
    spec:
       MORE: [...]
```

now, if i do a `helm upgrade ...` with no changes then the pods are updated, but still get the same `provider.kubernetes: no plans for deployment updates found for this event` in keel logs
