### ISSUE TITLE
DaemonSet Pods not being updated

### ISSUE THREAD

**Issue by gdvalderrama** [keel-hq/keel#200]
We just updated keel to 0.9.0-rc1, and set the labels and annotations necessary on our DaemonSet, but even after the image changes, the Pods aren't being replaced.

Keel is working perfectly on our Deployments.

Our DamonSet yaml:

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: scalyr-agent-2
  labels:
    app: scalyr-agent-2
    keel.sh/trigger: poll
    keel.sh/policy: force   # for latest
  annotations:
    keel.sh/pollSchedule: "@every 1m"
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: scalyr-agent-2
  template:
    metadata:
      labels:
        app: scalyr-agent-2
    spec:
      containers:
      - name: scalyr-agent
        image: index.docker.io/witei/logger-kubernetes:latest
        imagePullPolicy: Always
        env:
          - name: SCALYR_API_KEY
            valueFrom:
              secretKeyRef:
                name: scalyr-api-key
                key: scalyr-api-key
        resources:
          limits:
            memory: 500Mi
        volumeMounts:
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: dockersock
          mountPath: /var/scalyr/docker.sock
      volumes:
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      imagePullSecrets:
      - name: docker-registry-credentials
```
