### ISSUE TITLE
How I can use keel without webhookrelayd?

### ISSUE THREAD

**Issue by compozitor** [keel-hq/keel#249]
I need't use a webhookrelayd in my project. How I can right take off it in yaml file?

**Comment by rusenask** [comment]
Hi, there's no need to deploy it. Although I see that the code that generates deployments from helm chart is slightly broken and adds the sidecar when it shouldn't. Check https://github.com/keel-hq/keel/blob/master/hack/deployment.sample.yml for an example.

**Comment by compozitor** [comment]
I don't now why but this file https://github.com/keel-hq/keel/blob/master/hack/deployment.sample.yml  don't work.

**Comment by rusenask** [comment]
anything in the logs?

**Comment by compozitor** [comment]
Help me please! How I can see keel logs?

**Comment by rusenask** [comment]
Depends on the namespace where you have it.

First, find out the pod:
```
 kubectl get pods --all-namespaces       
NAMESPACE          NAME                                                       READY     STATUS    RESTARTS   AGE
keel               keel-7cfd989f8c-77xwc                                      1/1       Running   0          49d
kube-system        event-exporter-v0.2.1-5f5b89fcc8-zvcf6                     2/2       Running   0          11d
kube-system        fluentd-gcp-scaler-7c5db745fc-b9cqb                        1/1       Running   0          11d
kube-system        fluentd-gcp-v3.0.0-4p4lr                                   2/2       Running   0          11d
```
Now, when you see the pod and namespace, you can check the logs:
```
kubectl logs -n keel keel-7cfd989f8c-77xwc
```

**Comment by compozitor** [comment]
File https://github.com/keel-hq/keel/blob/master/hack/deployment.sample.yml don't create a pod with keel.

**Comment by rusenask** [comment]
```
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keel
  namespace: kube-system
  labels:
      name: "keel"
spec:
  replicas: 1
  template:
    metadata:
      name: keel
      labels:
        app: keel
    spec:
      serviceAccountName: keel
      containers:
        - image: keelhq/keel:0.9.5
          imagePullPolicy: Always
          env:
            - name: PROJECT_ID
              value: "my-project-id"
          name: keel
          command: ["/bin/keel"]
          ports:
            - containerPort: 9300
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9300
            initialDelaySeconds: 30
            timeoutSeconds: 10
```
Okay, if you just create this one, you can do:

```
kubectl logs -n kube-system deployment/keel
```
