### ISSUE TITLE
CronJob support.

### ISSUE THREAD

**Issue by Antiarchitect** [keel-hq/keel#251]
Kubernetes has CronJob entity and it's important to manage Deployments and CronJob images consistently. Please add CronJob support.

CronJob example:
```
application/job/cronjob.yaml  
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
```

**Comment by rusenask** [comment]
hi @Antiarchitect, please try out cron jobs! :)

Example:

```yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
  labels: 
    # force policy will ensure that deployment is updated
    # even when tag is unchanged (latest remains)
    keel.sh/policy: force
    keel.sh/trigger: poll
  annotations:
    keel.sh/pollSchedule: "@every 30s"
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: keelhq/cron-example:latest            
          restartPolicy: OnFailure
```
