### ISSUE TITLE
Default 0.9.5 setup with chart 0.6.2 on GKE renders pod in CrashLoopBackOff

### ISSUE THREAD

**Issue by caio1982** [keel-hq/keel#254]
Just followed the default steps to install it after cloning the repo and got this:

```
helm upgrade --install keel --namespace=keel ./chart/keel/ --set helmProvider.enabled="false" --set rbac.enabled="false" --set slack.enabled="false"
```

I needed RBAC disabled because this is running on GKE. So...

```
MacBook-Air:keel caio1982$   kubectl --namespace=keel get pods -l "app=keel"
NAME                   READY     STATUS             RESTARTS   AGE
keel-d575f68c7-m5x72   0/1       CrashLoopBackOff   5          3m
```

```
MacBook-Air:keel caio1982$ kubectl logs -n keel keel-d575f68c7-m5x72
time="2018-08-23T17:34:14Z" level=info msg="extension.notification: sender registered" name=hipchat
time="2018-08-23T17:34:14Z" level=info msg="extension.notification: sender registered" name=mattermost
time="2018-08-23T17:34:14Z" level=info msg="extension.notification: sender registered" name=slack
time="2018-08-23T17:34:14Z" level=info msg="extension.notification: sender registered" name=webhook
time="2018-08-23T17:34:14Z" level=info msg="extension.credentialshelper: helper registered" name=aws
time="2018-08-23T17:34:14Z" level=info msg="bot: registered" name=slack
time="2018-08-23T17:34:14Z" level=info msg="keel starting..." arch=amd64 build_date=2018-06-25T212350Z go_version=go1.10.3 os=linux revision=73b16284 version=0.9.5
time="2018-08-23T17:34:14Z" level=info msg="provider.kubernetes: using in-cluster configuration"
time="2018-08-23T17:34:14Z" level=fatal msg="main: failed to initialise kube-kv" error="configmaps \"approvals\" is forbidden: User \"system:serviceaccount:keel:keel\" cannot get configmaps in the namespace \"keel\": Unknown user \"system:serviceaccount:keel:keel\"" namespace=keel
```

Why is it still trying to use such service account if RBAC is disabled?

Why is it still trying to set up the Slack integration bot if Slack is disabled?

😥

**Comment by rusenask** [comment]
Hi, I also run it on GKE. I use https://github.com/keel-hq/keel/blob/master/hack/deployment.sample.yml as there's not much need for the Helm. Could you try deploying it? Just update to the newest version. I think those auto generated ones have some problems.

**Comment by caio1982** [comment]
Hey @rusenask, I did enable it via https://console.cloud.google.com/flows/enableapi?apiid=pubsub and even recreated the service account in the cluster right after, just in case, still the same error appears inside the pod's log though... any idea of what I can debug/investigate? Does it sound wrong what I am doing installation-wise?

**Comment by rusenask** [comment]
The problem with the node pool pubsub permissions is that you cannot enable on an already created pool, new pool has to be created. Not sure why GKE manages permissions this way :)

**Comment by caio1982** [comment]
Well, after a few hours struggling to cordon/drain my nodes and create a new pool with PubSub enabled (it is now) and recreating my stuff to deploy Keel once again (also recreating the service secret etc), I still get the same error @rusenask 😔

```
time="2018-08-24T15:57:50Z" level=fatal msg="main: failed to initialise kube-kv" error="configmaps \"approvals\" is forbidden: User \"system:serviceaccount:keel:default\" cannot get configmaps in the namespace \"kube-system\": Unknown user \"system:serviceaccount:keel:default\"" namespace=kube-system
```

I think the log message is very confusing, I have no idea what is wrong by looking at it. I have practically redeployed all my stuff onto a new pool with brand new nodes with PubSub... using the latest GKE stable version available...

**Comment by caio1982** [comment]
Oh! Wait! Keel only supports running in `kube-system`?

**Comment by rusenask** [comment]
So there were several issues, one was with the pubsub but this service account still persist. I personally don't add that part:
```
+            - name: GOOGLE_APPLICATION_CREDENTIALS 
+              value: "/var/secrets/google/key.json"  
```
as with the pubsub enabled for your node pool, you don't need it. Maybe because of that service account something happens to the user? Seems like k8s client-go can't create a config map inside that namespace

**Comment by rusenask** [comment]
Here's my deployment:

```yaml
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  annotations:
    kubernetes.io/service-account.name: keel    
  name: keel
  namespace: keel
  labels: 
      name: "keel"      
      keel.sh/policy: minor
spec:
  replicas: 1
  template:
    metadata:
      name: keel
      labels:
        app: keel      
    spec:
      containers:                    
        - image: keelhq/keel:0.9.5
          imagePullPolicy: Always
          env:                         
            - name: PUBSUB
              value: "1"
            - name: PROJECT_ID
              value: "<set yours>"
          name: keel
          command: ["/bin/keel"]
          ports:
            - containerPort: 9300       
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9300
            initialDelaySeconds: 30
            timeoutSeconds: 10
```

**Comment by caio1982** [comment]
That's really strange, I still get that freaky `Unknown user` error with your deployment, which makes me think Keel needs something from GKE that is not standard in my cluster? But my cluster is a standard clean one... other ideas of what to debug @rusenask on my end?

**Comment by caio1982** [comment]
I mean, why Keel keeps complaining about `kube-system` even with your deployment to `keel` namespace?

**Comment by caio1982** [comment]
Ok @rusenask I managed to get this running, but with a very sub-optimal approach so I would need your feedback about it as I think it is not secure. In my opinion Keel might be configured with a different namespace but it is always trying its perms from kube-system and specifically to get config maps out of it. This is hackish but it worked:

```
kubectl create clusterrolebinding add-on-cluster-admin  --clusterrole=cluster-admin  --serviceaccount=kube-system:default
```

That makes Keel starts ok, as per other Helm users having similar problems (even though I am using your deployment file).

See these related reports:

- https://github.com/helm/helm/issues/2687
- https://medium.com/google-cloud/initial-breakthrough-in-google-kubernetes-engine-gke-bd84d72870e4
- https://github.com/kubernetes/dashboard/issues/2326
- https://github.com/kubeflow/tf-operator/issues/106
- https://stackoverflow.com/questions/46672523/helm-list-cannot-list-configmaps-in-the-namespace-kube-system

**Comment by caio1982** [comment]
It is running but I cannot get any GCR poll to succeed now...

```
time="2018-08-24T18:40:49Z" level=error msg="trigger.poll.RepositoryWatcher.addJob: failed to get image digest" error="Get https://gcr.io/v2/nymos-dev/nympay-kubernetes-playground/manifests/latest: http: non-successful response (status=401 body=\"{\\\"errors\\\":[{\\\"code\\\":\\\"UNAUTHORIZED\\\",\\\"message\\\":\\\"Requested repository does not match bearer token resource: nymos-dev/nympay-kubernetes-playground\\\"}]}\")" image="nymos-dev/nympay-kubernetes-playground:latest"
```
I think the docs are not that clear man...

**Comment by rajasaur** [comment]
I got around the " error="configmaps \"approvals\" is forbidden" problem by enabling RBAC as the helm chart creates the role binding only if RBAC is enabled?

As noted above, maybe we should just run the chart using the default service account if rbac is not enabled. Given that RBAC is generally available since k8s 1.8, should the helm chart default to rbac: true instead of rbac: false ?

**Comment by rusenask** [comment]
Regarding GCR poll, it won't work as it uses different authentication mechanism rather than imagePullSecrets. We would need to build something like AWS ECR custom secrets getter. Although it's a lot easier just to use pubsub. 

I will try to create a new GKE cluster and check the setup.

**Comment by ggrocco** [comment]
Hi, I'm trying to install on my custom cluster on AWS, I'm getting the same error:
```bash
level=fatal msg="main: failed to initialise kube-kv" error="configmaps \"approvals\" is forbidden: User \"system:serviceaccount:kube-system:default\" cannot get configmaps in the namespace \"kube-system\": System accounts cannot be authorized via webhook." namespace=kube-system`
```
I try to install using Helm 
`helm install -n keel --namespace=kube-system stable/keel -f my-values.yaml`

```yaml
helmProvider:
  enabled: true
  tillerAddress: "tiller-deploy.tiller.svc.cluster.local:44134" # my tiller is on tiller namespace

ecr:
  enabled: true
  accessKeyId: "THE AWS KEY"
  secretAccessKey: "THE AWS SECRET"
  region: "us-east-1"

slack:
  enabled: true
  botName: "keel"
  token: "My TOKEN"
  channel: "some-channel"
  approvalsChannel: "same-channel"

rbac:
  enabled: true
```

What I'm doing wrong?!
