### ISSUE TITLE
Using webhookrelayd with Keel 

### ISSUE THREAD

**Issue by rajasaur** [keel-hq/keel#256]
This is a newbie question but I wasn't able to figure out how to get this working.

I wanted to expose Keel's APIs through webhookrelay so that I can make a call like
https://my.webhookrelay.com/v1/webhooks/<uniqueid\>/v1/approvals to get through to Approvals or to trigger the deployment. 

I am using helm charts and enabled the webhookrelayd section, filling in the bucket, secret and key. The containers are up and the logs on the webhookrelayd indicate this:
`{"level":"info","ts":1535186129.9301355,"msg":"webhook relay ready...","host":"my.webhookrelay.com:8080"}`

I am not able to figure out what the input endpoint(uniqueid in the URL) is so that the calls can be made to that endpoint. Since the webhookrelayd container just runs
/relayd (And uses the KEY,SECRET and BUCKET) from the environment variable, how will it know to forward to the localhost:9300 that Keel exposes?

From the docs, 
`
relay forward -help
`
indicates that if we dont provide any destinations, it will start a relay for *all* endpoints. 

Can you please clarify how I can use the webhookrelay.com service so that the external requests (trigger/approval) can be made to reach the container.

PS: I can definitely do a NodePort on the Keel service and get this working, but just wanted to see how this service will work.

**Comment by rusenask** [comment]
Hi, please go to your account buckets page here: https://my.webhookrelay.com/buckets and ensure that the bucket exists. If it doesn't (since you need to create one), create it. 

Buckets page (create button top right)
![create_bucket](https://user-images.githubusercontent.com/9080105/44617133-6f6e8280-a855-11e8-9283-2f940547d199.png)

When creating a bucket, it has to match the one you specified in your webhookrelayd container:
![bucket_keel](https://user-images.githubusercontent.com/9080105/44617146-a04eb780-a855-11e8-8583-4d538c401b11.png)

Configure it (make sure on the output you tick "internal" checkbox):
![configure_bucket](https://user-images.githubusercontent.com/9080105/44617137-86ad7000-a855-11e8-9643-f052a225c73e.png)

I have also wrote a blog post how to setup end-to-end workflow: https://keel.sh/v1/examples/push-to-deploy.html

Will write another one for the policy based updates :)

**Comment by rajasaur** [comment]
Thanks for the quick response @rusenask . I did try that (Setup the bucket already, which was updated in the helm values.yaml file). 
I got an URL like 
https://my.webhookrelay.com/v1/webhooks/e22f0e73-37c7-49c8-8724-206219fb02fd when setting up the input on the bucket. On the output, I just mentioned http://localhost:9300 and clicked on "Internal" as you mentioned.

Now when I try to see what approvals I have (Nothing at the minute as its not fully setup), I expected to see an output of
`
[]
`
which is what I get when I go through NodePort.

But if I do something like
curl https://my.webhookrelay.com/v1/webhooks/e22f0e73-37c7-49c8-8724-206219fb02fd/v1/approvals

I get my dashboard page itself (of webhookrelay.com) rather than []. Not sure what I am missing.

**Comment by rusenask** [comment]
Oh, the webhooks are one way so you can't get the response. If you want two-way then you have to use tunnels. That webhookrelayd does support tunnels so you could use it as a sidecar but you could also use this ingress controller (would require for you to create a service and ingress.yaml):
https://webhookrelay.com/v1/examples/relay-ingress.html


## Sidecar approach would be something like:

1. Create a tunnel
```
$ relay tunnel create --name keel --destination http://localhost:9300
7a3ecl2hftajr5qgeuccs4.webrelay.io<---->http://localhost:9300
```

2. Modify sidecar with `--mode tunnel`:

```
// the rest of config
        - name: webhookrelayd
          image: "webhookrelay/webhookrelayd:latest"
          imagePullPolicy: always
          command: ["/relayd", "--mode", "tunnel"]
          env:
            - name: KEY
              valueFrom:
                secretKeyRef:
                  name: keel-webhookrelay
                  key: key
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: keel-webhookrelay
                  key: secret
            - name: TUNNELS
              value: "keel"
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
```
