### ISSUE TITLE
ECR Polling is failing on get credentions

### ISSUE THREAD

**Issue by ggrocco** [keel-hq/keel#260]
Hi, based on the documentation, is confusing but I add on the installation the ECR information:

```yaml
ecr:
  enabled: true
  accessKeyId: "MY_REAL_ACCESS_KEY"
  secretAccessKey: "MY_REAL_SECRED_KEY"
  region: "us-east-1"
```
This creates the secret called `keel-aws-ecr`, with has my `MY_REAL_SECRED_KEY`.

But looking at the logs I'm seeing the warning and error on getting the access to the ECR:

```
time="2018-08-30T15:39:09Z" level=warning msg="secrets.defaultGetter: failed to get secret" error="secrets \"aws-ecr-credentials\" not found" image=MYPATHID.dkr.ecr.us-east-1.amazonaws.com/test_app namespace=app-staging secret_ref=aws-ecr-credentials
time="2018-08-30T15:39:09Z" level=warning msg="secrets.defaultGetter: failed to get secret" error="secrets \"aws-ecr-credentials\" not found" image=MYPATHID.dkr.ecr.us-east-1.amazonaws.com/test_app namespace=app-staging secret_ref=aws-ecr-credentials
time="2018-08-30T15:39:09Z" level=warning msg="secrets.defaultGetter.lookupSecrets: docker credentials were not found among secrets" image=MYPATHID.dkr.ecr.us-east-1.amazonaws.com/test_app namespace=app-staging provider=helm registry=MYPATHID.dkr.ecr.us-east-1.amazonaws.com secrets="[aws-ecr-credentials aws-ecr-credentials]"
time="2018-08-30T15:39:10Z" level=error msg="trigger.poll.RepositoryWatcher.addJob: failed to get image digest" error="Get https://MYPATHID.dkr.ecr.us-east-1.amazonaws.com/v2/test_app/manifests/1.48.3628: http: non-successful response (status=401 body=\"Not Authorized\\n\")" image="test_app:1.48.3628"
time="2018-08-30T15:39:10Z" level=error msg="trigger.poll.RepositoryWatcher.Watch: failed to add image watch job" error="Get https://MYPATHID.dkr.ecr.us-east-1.amazonaws.com/v2/test_app/manifests/1.48.3628: http: non-successful response (status=401 body=\"Not Authorized\\n\")" image="namespace:app-staging,image:MYPATHID.dkr.ecr.us-east-1.amazonaws.com/test_app,provider:helm,trigger:poll,sched:@every 3m,secrets:[aws-ecr-credentials aws-ecr-credentials]"
```

And I'm not so good Go reader, but looks to me Keel is trying to get the secret from the same place as the as the Chart values `/keel/secrets/secrets.go:222` 

This is some configurations error or something is really brock?

**Comment by rusenask** [comment]
is MY_REAL_ACCESS_KEY an actual string that contains ID? 

Looking at the helm chart it does seem a bit weird:
```
{{- if .Values.ecr.enabled }}
            # Enable AWS ECR
            - name: AWS_ACCESS_KEY_ID
              value: "{{ .Values.ecr.accessKeyId }}"
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "keel.name" . }}-aws-ecr
                  key: secretAccessKey
            - name: AWS_REGION
              value: "{{ .Values.ecr.region }}"
{{- end }}
```
@rimusz  this is probably not right? it takes ID from the values but access key is in the secret?
