### ISSUE TITLE
Notification channel different attributes names

### ISSUE THREAD

**Issue by ggrocco** [keel-hq/keel#261]
Hi, I'm using Helm and for definitions on helm we define like this:
```yaml
keel:
  # keel policy (all/major/minor/patch/force)
  policy: all
  # trigger type, defaults to events such as pubsub, webhooks
  trigger: poll
  # polling schedule
  pollSchedule: "@every 3m"
  # chat channels to sent notification to
  notificationChannels:
    - "#devs-channel"
  # approvals required to proceed with an update
  approvals: 0
  # images to track and update
  images:
    - repository: image.repository
      tag: image.tag
```

But on documentation, the `notificationChannels` is called `notify` with is used on Deployment as annotations like 

```yaml
annotations:
      keel.sh/notify: chan1,chan2
```

I believe to make sense try to keep the same notation on both sides, I know the `notificationChannels` accept an Array and the  `notify` a string to split by `,`.  I could open a PR for change `notify` to `notificationChannels` or vice versa. This could help?

**Comment by rusenask** [comment]
yes, makes sense. But to avoid breaking changes for now, maybe you could choose a different key:
```
keel:
  # keel policy (all/major/minor/patch/force)
  policy: all
  # trigger type, defaults to events such as pubsub, webhooks
  trigger: poll
  # polling schedule
  pollSchedule: "@every 3m"
  notify: "chan1, chan2"  # < ---------------- new one
  # chat channels to sent notification to
  notificationChannels:
    - "#devs-channel"
  # approvals required to proceed with an update
  approvals: 0
  # images to track and update
  images:
    - repository: image.repository
      tag: image.tag
```

PRs are always welcome :)
