### ISSUE TITLE
match-tag=true in helm deployments

### ISSUE THREAD

**Issue by jeremyjh** [keel-hq/keel#273]
I presently have two releases on the same cluster, both using the same base image but different tags and keel policies. The prod release is using semver, staging is using a label called "master-latest". I do not want staging to get updated when new semver tags are published, but that is what is happening. Otherwise, everything works properly (prod only gets updated on revision bump of semver, staging gets master-latest updates).

It seems like match-tag: true is not being respected, but I'm not even sure I'm specifying it properly as I couldn't find a helm example. I tried both match-tag: "true" and match-tag: true, but I don't see evidence in the logs that this is considered.

The helm release values look like this:

prod/values.yaml
```yaml
image:
  tag: 0.1.1
  pullPolicy: IfNotPresent


keel:
  policy: patch
  images:
    - repository: image.repository
      tag: image.tag

```

staging/values.yaml
```yaml
image:
  tag: master-latest
  pullPolicy: Always

keel:
  policy: force
  match-tag: "true"
  images:
    - repository: image.repository
      tag: image.tag
```

Keel logs for a new semver tag look like this:
```
time="2018-09-09T19:36:06Z" level=info msg="provider.helm: processing event" registry= repository=gcr.io/devhook-214711/devhook-web tag=0.1.3
time="2018-09-09T19:36:06Z" level=info msg="provider.kubernetes: processing event" registry= repository=gcr.io/devhook-214711/devhook-web tag=0.1.3
time="2018-09-09T19:36:06Z" level=info msg="provider.kubernetes: no plans for deployment updates found for this event" image=gcr.io/devhook-214711/devhook-web tag=0.1.3
time="2018-09-09T19:36:06Z" level=info msg="provider.helm: current image version" container_image=gcr.io/devhook-214711/devhook-web current_version=0.1.2 name=devhook-web-prod namespace=default policy=patch
time="2018-09-09T19:36:06Z" level=info msg="provider.helm: checked version, deciding whether to update" container_image=gcr.io/devhook-214711/devhook-web current_version=0.1.2 name=devhook-web-prod namespace=default new_version=0.1.3 policy=patch should_update=true
time="2018-09-09T19:36:06Z" level=info msg="provider.helm: impacted release tags found" container_image=gcr.io/devhook-214711/devhook-web policy=patch target_image=gcr.io/devhook-214711/devhook-web target_image_tag=0.1.3
time="2018-09-09T19:36:06Z" level=info msg="provider.helm: impacted release container found" parsed_image="gcr.io/devhook-214711/devhook-web:master-latest" policy=force target_image=gcr.io/devhook-214711/devhook-web target_image_tag=0.1.3
time="2018-09-09T19:36:06Z" level=info msg="provider.helm: images do not match, ignoring" parsed_image_name="index.docker.io/keelhq/keel:0.10.0" target_image_name=gcr.io/devhook-214711/devhook-web
time="2018-09-09T19:36:18Z" level=info msg="provider.helm: release updated" release=devhook-web-prod version=3
time="2018-09-09T19:36:30Z" level=info msg="provider.helm: release updated" release=devhook-web-staging version=4
```

**Comment by rusenask** [comment]
Hi, match-tag is not an option for Helm provider. Only recently it was added and is still not released, although I will probably release it this week. You can try out keel's alpha tag, then in the keel config use `matchTag` as a bool:

```yaml
keel:
  policy: force
  matchTag: bool
  images:
    - repository: image.repository
      tag: image.tag
```
