### ISSUE TITLE
Templated Helm values not working

### ISSUE THREAD

**Issue by The-Loeki** [keel-hq/keel#294]
Helm introduced the `tpl` function a few releases back.
This leads to the following interesting possibility:

`Chart.yaml`:
```yaml
appVersion: 1.7
```

`deployment.yaml`:
```yaml
      containers:
      - image: {{ .Values.image }}:{{ tpl .Values.imageTag . }}
```

`values.yaml`:
```yaml
image: anImageYesYes
imageTag: v{{ .Chart.AppVersion }}-alpine
```

Which leads to Keel bugging out like:
```
level=error msg="provider.helm: failed to parse image" error="Error parsing reference: \"example.com/etc/anImageYesYes:v{{ .Chart.AppVersion }}\" is not a valid repository/tag, error: invalid reference format" repository_name=image repository_tag=imageTag
```

**Comment by rusenask** [comment]
updating Helm library dependencies in keel might do the job as we are using `"k8s.io/helm/pkg/chartutil"` to parse config. Could you create an example that I could use to reproduce and test against?

**Comment by The-Loeki** [comment]
Sure! Here's a modified version of Traefik for example: https://gitlab.com/ors-it/oss/helm-traefik

**Comment by WesleyCharlesBlake** [comment]
Can confirm the same behavior here:

```time="2018-10-19T13:05:13Z" level=error msg="provider.helm: failed to parse image" error="Error parsing reference: \"poetapp/node:v{{ .Chart.AppVersion }}\" is not a valid repository/tag, error: invalid reference format" repository_name=image.repository repository_tag=image.tag
```

Deployment template: 
```
...
          image: {{ .Values.image.repository }}:{{ tpl .Values.image.tag . }}
...
```

When I do a dry run, I can confirm that helm is parsing the correct version inherited from the Chart.yaml:

Something to note though, is that the COMPUTED vals in helm show:

```
COMPUTED VALUES:
...
image:
  pullPolicy: IfNotPresent
  repository: poetapp/node
  tag: v{{ .Chart.AppVersion }}
...
```

But the manifests indicate the correctly parsed tag:

```
MANIFEST:
...
# Source: poet-node/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: test-tpl-ver-poet-node
  labels:
    app: poet-node
    chart: poet-node-1.0.6
    release: test-tpl-ver
    heritage: Tiller
spec:
  replicas: 1
  revisionHistoryLimit: 5
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: poet-node
      release: test-tpl-ver
  template:
    metadata:
      labels:
        app: poet-node
        release: test-tpl-ver
    spec:
      containers:
        - name: poet-node
          image: poetapp/node:v1.8.1
...
```

appending the `--dry-run --debug` args to the `helm install ..` command will give the above info which can help with trouble shooting as well
