### ISSUE TITLE
Feature Request: Helm provider for approvalDeadline

### ISSUE THREAD

**Issue by Martin-4Spaces** [keel-hq/keel#304]
I would like to be able to control the approvalDeadline from helm. 
Thanks :)

**Comment by Martin-4Spaces** [comment]
Another note.
The comments tell me the deadline is 24 hours
```
// KeelApprovalDeadlineDefault - default deadline in hours
const KeelApprovalDeadlineDefault = 24 
```
But I am think it might be only 24 minutes :D
I'm, not sure what this will do
'time.Now().Add(time.Duration(deadline) * time.Hour)'
But they do disappear after roughly 24 minutes.

**Comment by rusenask** [comment]
added some logging and an e2e test, regarding 24 minutes: https://play.golang.org/p/Oc1CbU49rex not sure what happens :/ 

Example helm deadline:

```
keel:
  # keel policy (all/major/minor/patch/force)
  policy: all
  # trigger type, defaults to events such as pubsub, webhooks
  trigger: poll
  # polling schedule
  pollSchedule: "@every 1m"
  # approvals required to proceed with an update
  approvals: 1
  # approvals deadline in hours
  approvalDeadline: 24 
  # images to track and update
  images:
    - repository: image.repository
      tag: image.tag
```
