### ISSUE TITLE
docker credentials were not found among secrets

### ISSUE THREAD

**Issue by travisghansen** [keel-hq/keel#310]
I suspect this has something to do with the fact that the secret (which does exist) does **not** reference the registry storing the image but rather a private registry (not docker hub).  As a matter of consistency I add my private registry credentials to all deployments (some need them some don't).

In other words, the deployment has pull secrets, just none of them reference the registry used by the deployment.

```
time="2018-11-23T04:53:23Z" level=warning msg="secrets.defaultGetter.lookupSecrets: docker credentials were not found among secrets" image=index.docker.io/linuxserver/unifi namespace=default provider=kubernetes registry=index.docker.io secrets="[registry-credentials]"
```

**Comment by travisghansen** [comment]
@rusenask yeah, my suspicions seem to be correct.  Here are my observations:

1. If the deployment provides registry secrets, but none of the registries auth'd in the secret(s) reference the container image registry then it fails (my original problem).
2. If the deployment omits registry secrets all is fine.
3. If the registry secrets (at least for docker hub) do not 'own' the image, then you end up with problems as well (`UNAUTHORIZED`).  This could be circumstantial, I haven't nailed this down yet.

All of the scenarios pose some interesting problems, especially if the deployment has more than 1 container/image and those may or may not cross registries.  Or even within the same registry, but projects you may or may not own (ie: 2 containers from docker hub, 1 I own, the other I do not).

See yaml below:
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: keeltest
---
apiVersion: v1
kind: Secret
metadata:
  namespace: keeltest
  name: registry-credentials
type: kubernetes.io/dockerconfigjson
data:
  # https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  # works (assuming valid credentials AND a repo the user owns)
  # {"auths":{"https://index.docker.io/v1/":{"username":"foo","password":"bar","email":"foo@bar","auth":"Zm9vOmJhcg=="}}}
  #.dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJmb28iLCJwYXNzd29yZCI6ImJhciIsImVtYWlsIjoiZm9vQGJhciIsImF1dGgiOiJabTl2T21KaGNnPT0ifX19
  
  # does not work
  # {"auths":{"https://cr.foo.bar":{"username":"foo","password":"bar","email":"foo@bar","auth":"Zm9vOmJhcg=="}}}
  #.dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2NyLmZvby5iYXIiOnsidXNlcm5hbWUiOiJmb28iLCJwYXNzd29yZCI6ImJhciIsImVtYWlsIjoiZm9vQGJhciIsImF1dGgiOiJabTl2T21KaGNnPT0ifX19
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: keeltest
  labels:
    app: busybox
    keel.sh/trigger: poll
    keel.sh/policy: force
    keel.sh/match-tag: "true"
  annotations:
    keel.sh/pollSchedule: "@every 10m"
  name: busybox
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - image: busybox:latest
        name: busybox
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello; sleep 5;done"]
      restartPolicy: Always
      imagePullSecrets:
      - name: registry-credentials
```
