### ISSUE TITLE
Failed to get image digest when using imagePullSecrets of dependency chart

### ISSUE THREAD

**Issue by yosbeleg89** [keel-hq/keel#314]
We have a chart, let's call it `app` where we had a keel configuration like:

```yaml
keel:
  # keel policy (all/major/minor/patch/force)
  policy: all
  # trigger type, defaults to events such as pubsub, webhooks
  trigger: poll
  # polling schedule
  pollSchedule: "@every 1m"
  # approvals required to proceed with an update
  approvals: 0
  # images to track and update
  
  images:
    - repository: image.repository
      tag: image.tag
      imagePullSecret: image.imagePullSecret
```

This was working fine and Keel was able to retrieve the images fine, the secret is for an Azure Container Registry. Now we have a new chart that have the `app` chart as a dependency, we created in this new chart a keel configuration like:

```yaml
...
app:
  ingress:
    hosts:
      - www.somedomain.com

keel:
  # keel policy (all/major/minor/patch/force)
  policy: all
  # trigger type, defaults to events such as pubsub, webhooks
  trigger: poll
  # polling schedule
  pollSchedule: "@every 1m"
  # approvals required to proceed with an update
  approvals: 0
  # images to track and update
  
  images:
    - repository: app.image.repository
      tag: app.image.tag
      imagePullSecret: app.image.imagePullSecret
```

We want Keel to update the dependency images and use the `imagePullSecret` configured in that chart.

For some reason Keel in correctly getting the image and tag, but is unable to access the registry:

```
time="2018-11-26T23:45:41Z" level=error msg="trigger.poll.RepositoryWatcher.addJob: failed to get image digest" error="Get https://containername.azurecr.io/v2/app/manifests/1.0.0: http: non-successful response (status=401 body=\"{\\\"errors\\\":[{\\\"code\\\":\\\"UNAUTHORIZED\\\",\\\"message\\\":\\\"authentication required\\\",\\\"detail\\\":[{\\\"Type\\\":\\\"repository\\\",\\\"Name\\\":\\\"app\\\",\\\"Action\\\":\\\"pull\\\"}]}]}\\n\")" image="app:1.0.0"
time="2018-11-26T23:45:41Z" level=error msg="trigger.poll.RepositoryWatcher.Watch: failed to add image watch job" error="Get https://containername.azurecr.io/v2/app/manifests/1.0.0: http: non-successful response (status=401 body=\"{\\\"errors\\\":[{\\\"code\\\":\\\"UNAUTHORIZED\\\",\\\"message\\\":\\\"authentication required\\\",\\\"detail\\\":[{\\\"Type\\\":\\\"repository\\\",\\\"Name\\\":\\\"app\\\",\\\"Action\\\":\\\"pull\\\"}]}]}\\n\")" image="namespace:dev,containername.azurecr.io/app,provider:helm,trigger:poll,sched:@every 1m,secrets:[]"
time="2018-11-26T23:45:41Z" level=error msg="trigger.poll.manager: got error(-s) while watching images" error="encountered errors while adding images: Get https://containername.azurecr.io/v2/app/manifests/1.0.0: http: non-successful response (status=401 body=\"{\\\"errors\\\":[{\\\"code\\\":\\\"UNAUTHORIZED\\\",\\\"message\\\":\\\"authentication required\\\",\\\"detail\\\":[{\\\"Type\\\":\\\"repository\\\",\\\"Name\\\":\\\"app\\\",\\\"Action\\\":\\\"pull\\\"}]}]}\\n\")"
```

*Keel version*: 0.12.0
