### ISSUE TITLE
unsupported protocol scheme

### ISSUE THREAD

**Issue by yosbeleg89** [keel-hq/keel#333]
Keel is failing trying to get the latest version of an image, I can see in the logs:

`level=error msg="trigger.poll.WatchRepositoryTagsJob: failed to get repository" error="Get /v2/app/tags/list?last=1.0.955&n=100&orderby=: unsupported protocol scheme \"\"" image="app:1.0.955"`

I noticed that the url being used does not contain the registry url which is hosted in an ACR, I also tried to fetch the tags doing a `curl` and it does anwser to that query without error. I'm using version `0.13.0`

Thanks

**Comment by rusenask** [comment]
hi, quite weird. What's the image name? does it contain the registry URL?
With Azure it would be better to use webhooks as you wouldn't have to care about authentication.

**Comment by yosbeleg89** [comment]
Sorry for the delay, the image name is `app`. The chart contains the registry URL, but the log does not, I noticed that other logs contains it, which make me thinkg that the issue is related with the registry not present and that's why the scheme is invalid. This was working several days before, but when the number of tags in the registry increased it started to fail.

**Comment by rusenask** [comment]
Hi, hows doe it look like in the chart template where it uses that image? For example Keel chart:
```
  containers:
        - name: keel
          # Note that we use appVersion to get images tag.
image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
```

**Comment by yosbeleg89** [comment]
It looks like in the deployment.yaml:

```YAML
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
```

and from the values.yaml:
```YAML
image:
  repository: myacr.azurecr.io/app
  tag: 1.0.888
```
