### ISSUE TITLE
Failed to add image watch job: i/o timeout 

### ISSUE THREAD

**Issue by lentzi90** [keel-hq/keel#335]
I'm trying to deploy keel using helm and having it update itself.
Unfortunately keel fails to add the image watch job due to i/o timeout.
I'm following the documentation [here](https://keel.sh/v1/guide/installation.html#Deploying-with-Helm) and have the following values file:
```yaml
helmProvider:
  enabled: true

keel:
  # keel policy (all/major/minor/patch/force)
  policy: all
  # trigger type, defaults to events such as pubsub, webhooks
  trigger: poll
  # polling schedule
  pollSchedule: "@every 5m"
  # images to track and update
  images:
    - repository: image.repository
      tag: image.tag
```

Is there a way to increase this timeout? Anything else I'm doing wrong?

Here is a sample log entry:
```
time="2019-01-19T14:10:21Z" level=error msg="trigger.poll.RepositoryWatcher.Watch: failed to add image watch job" error="Get https://index.docker.io/v2/keelhq/keel/manifests/0.12.0: Get https://auth.docker.io/token?scope=repository%3Akeelhq%2Fkeel%3Apull&service=registry.docker.io: dial tcp: i/o timeout" image="namespace:kube-system,image:index.docker.io/keelhq/keel,provider:helm,trigger:poll,sched:@every 5m,secrets:[]"
time="2019-01-19T14:10:21Z" level=error msg="trigger.poll.manager: got error(-s) while watching images" error="encountered errors while adding images: Get https://index.docker.io/v2/keelhq/keel/manifests/0.12.0: Get https://auth.docker.io/token?scope=repository%3Akeelhq%2Fkeel%3Apull&service=registry.docker.io: dial tcp: i/o timeout"
```
