### ISSUE TITLE
Failed to get tracked image with 24h schedule

### ISSUE THREAD

**Issue by yutongp** [keel-hq/keel#340]
I got following an error when polling image:
`time="2019-01-30T23:44:57Z" level=error msg="provider.defaultProviders: failed to get tracked images" error="context deadline exceeded" provider=helm`
if I set the `pollSchedule` to be `24h`.

I also tried with the same cluster, same image(dockerhub public image), same settings, but only changed the `pollSchedule` to be `5m`. Then it worked without any issue(so probably tiller is reachable).

Here is my keel setting:
```yaml
keel:
  # keel policy (all/major/minor/patch/force)
  policy: all
  # trigger type, defaults to events such as pubsub, webhooks
  trigger: poll
  # polling schedule
  pollSchedule: "@every 24h"
  # approvals required to proceed with an update
  approvals: 1
  # approvals deadline in hours
  approvalDeadline: 20
  # images to track and update
  images:
    - repository: image.core.repository
      tag: image.core.tag
```
