### ISSUE TITLE
Non-standart helm image tag

### ISSUE THREAD

**Issue by afoninsky** [keel-hq/keel#341]
Some custom charts have image and tag in one environment. Example: https://github.com/hashicorp/consul-helm/blob/master/values.yaml
```
image: "consul:1.3.1"
```

In this case following annotation does not work:
```
keel:
  images:
    - repository: image.repository
      tag: image.tag
```

Are there any workarounds?
