### ISSUE TITLE
Error while watching images from docker hub

### ISSUE THREAD

**Issue by WRidder** [keel-hq/keel#342]
My docker hub has a private image repository which I deployed to a local microk8s cluster.  I have a docker hub account, denoted `$USER`, and a project, denoted `$REPO`.  I'm using keel 0.13.

The deployment yaml:
```yaml 
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: $REPO
  namespace: default
  labels: 
      name: "wd"
      keel.sh/policy: major
      keel.sh/trigger: poll      
  annotations:
      keel.sh/pollSchedule: "@every 30s"
spec:
  replicas: 1
  template:
    metadata:
      name: $REPO
      labels:
        app: $REPO        
    spec:
      containers:                    
        - image: $USER/$REPO:0.0.19
          imagePullPolicy: Always            
          name: $REPO
          ports:
            - containerPort: 80    
          livenessProbe:
            httpGet:
              path: /healthz.html
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 10
          securityContext:
            privileged: true 
      imagePullSecrets:
        - name: dockerhubdeploycred
```

The secret has been created using:
```bash
kubectl create secret docker-registry dockerhubdeploycred --docker-server=docker.io --docker-username=$USER--docker-password=SOMEPASSWORD --docker-email=SOMEEMAIL
```

The error log
```
time="2019-02-06T14:06:31Z" level=error msg="trigger.poll.RepositoryWatcher.addJob: failed to get image digest" error="Get https://index.docker.io/v2/$USER/$REPO/manifests/0.0.19: dial tcp: i/o timeout" image="$USER/$REPO:0.0.19" password= username=

time="2019-02-06T14:06:31Z" level=error msg="trigger.poll.RepositoryWatcher.Watch: failed to add image watch job" error="Get https://index.docker.io/v2/$USER/$REPO/manifests/0.0.19: dial tcp: i/o timeout" image="namespace:default,image:index.docker.io/$USER/$REPO:0.0.19,provider:kubernetes,trigger:poll,sched:@every 30s,secrets:[dockerhubdeploycred]"

time="2019-02-06T14:06:31Z" level=error msg="trigger.poll.manager: got error(-s) while watching images" error="encountered errors while adding images: Get https://index.docker.io/v2/$USER/$REPO/manifests/0.0.19: dial tcp: i/o timeout"

time="2019-02-06T14:06:31Z" level=warning msg="secrets.defaultGetter.lookupSecrets: secret found but couldn't detect authentication for the desired registry" image=index.docker.io/$USER/$REPO namespace=default provider=kubernetes registry=index.docker.io secrets="[dockerhubdeploycred]"
```

The Keel deployment yaml:
```yaml
---
# Source: keel/templates/00-namespace.yaml

apiVersion: v1
kind: Namespace
metadata:
  name: "keel"

---
# Source: keel/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keel
  namespace: keel
  labels:
    app: keel
    chart: keel-0.7.0
    release: keel
    heritage: Tiller

---
# Source: keel/templates/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: keel
  namespace: keel
  labels:
    app: keel
    chart: keel-0.7.0
    release: keel
    heritage: Tiller
spec:
  type: LoadBalancer
  ports:
    - port: 9300
      targetPort: 9300
      protocol: TCP
      name: keel
  selector:
    app: keel
  sessionAffinity: None

---
# Source: keel/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: keel
  namespace: keel
  labels:
    app: keel
    chart: keel-0.7.0
    release: keel
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keel
      release: keel
  template:
    metadata:
      labels:
        app: keel
        release: keel
    spec:
      serviceAccountName: keel
      containers:
        - name: keel
          # Note that we use appVersion to get images tag.
          image: "keelhq/keel:0.13.0"
          imagePullPolicy: IfNotPresent
          command: ["/bin/keel"]
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            # Enable polling
            - name: POLL
              value: "1"
            # Enable GCR with pub/sub support
            - name: PROJECT_ID
              value: ""
            - name: PUBSUB
              value: "" # Set to '1' or 'true' to enable GCR pubsub
            # Enable AWS ECR
            - name: AWS_ACCESS_KEY_ID
              value: ""
            - name: AWS_SECRET_ACCESS_KEY
              value: ""
            - name: AWS_REGION
              value: ""
            # Enable webhook endpoint
            - name: WEBHOOK_ENDPOINT
              value: ""
            # Enable mattermost endpoint
            - name: MATTERMOST_ENDPOINT
              value: ""
            - name: SLACK_TOKEN
              value: ""
            - name: SLACK_CHANNELS
              value: ""
            - name: SLACK_APPROVALS_CHANNEL
              value: ""
            # Enable hipchat approvials and notification
            - name: HIPCHAT_TOKEN
              value: ""
            - name: HIPCHAT_CHANNELS
              value: ""
            - name: HIPCHAT_APPROVALS_CHANNEL
              value: ""
            - name: HIPCHAT_APPROVALS_BOT_NAME
              value: ""
            - name: HIPCHAT_APPROVALS_USER_NAME
              value: ""
            - name: HIPCHAT_APPROVALS_PASSWORT
              value: ""
            - name: NOTIFICATION_LEVEL
              value: "info"
            # Enable insecure registries
            - name: INSECURE_REGISTRY
              value: "true"
          ports:
            - containerPort: 9300
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9300
            initialDelaySeconds: 30
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
            

---
# Source: keel/templates/pod-disruption-budget.yaml

apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: keel
  namespace: keel
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: keel
```

My question is what could be the reason the polling is not working correctly in this setup?

Additional info:
When trying to use the local unsecured registry from microk8s, polling from this registry does not work either (no credentials need to be used in this case). The error log from Keel reads then:
```
time="2019-02-06T15:03:22Z" level=error msg="trigger.poll.RepositoryWatcher.addJob: failed to get image digest" error="Get https://localhost:32000/v2/$REPO/manifests/0.0.21: dial tcp: i/o timeout" image="$REPO:0.0.21" password= username=
time="2019-02-06T15:03:22Z" level=error msg="trigger.poll.RepositoryWatcher.Watch: failed to add image watch job" error="Get https://localhost:32000/v2/$REPO/manifests/0.0.21: dial tcp: i/o timeout" image="namespace:default,image:localhost:32000/$REPO:0.0.21,provider:kubernetes,trigger:poll,sched:@every 30s,secrets:[]"
time="2019-02-06T15:03:22Z" level=error msg="trigger.poll.manager: got error(-s) while watching images" error="encountered errors while adding images: Get https://localhost:32000/v2/$REPO/manifests/0.0.21: dial tcp: i/o timeout"
```
