### ISSUE TITLE
slack approval does not work

### ISSUE THREAD

**Issue by botzill** [keel-hq/keel#362]
Hi.

I setup slack bot properly(I think so) and I get notifications for image upgrades. 

<img width="651" alt="Screen Shot 2019-04-17 at 23 36 58" src="https://user-images.githubusercontent.com/4686040/56319247-d1c01e80-6169-11e9-85a7-dca80891aeab.png">

My bot

<img width="1003" alt="Screen Shot 2019-04-17 at 23 41 48" src="https://user-images.githubusercontent.com/4686040/56319462-75a9ca00-616a-11e9-95d8-5061e7d560bf.png">

But when I write back the approval messages does not work and I tried both ways, with bot and without `@keel`. 

I see nothing in logs related to that, no message that this approval is received. 

Using the latest keel: `keel:0.13.2`.

Thx.

**Comment by botzill** [comment]
My `slack` config is:

```
slack:
  enabled: true
  botName: "keel"
  token: "xoxb-491104275778-..."
  channel: "_k8s-stats"
  approvalsChannel: "_k8s-keel-approval"
```
