### ISSUE TITLE
Update image with the same tag via webhook

### ISSUE THREAD

**Issue by botzill** [keel-hq/keel#365]
Hi.

To speed up the development we don't have to increment version of the image, can be a fixed version or `latest`. I'm using the following config:

```
keel:
  # keel policy (all/major/minor/patch/force)
  policy: force
  # trigger type, defaults to events such as pubsub, webhooks
  trigger: default
  # polling schedule
  # pollSchedule: "@every 1m"
  # approvals required to proceed with an update
  approvals: 0
  # approvals deadline in hours
  approvalDeadline: 24
  # images to track and update
  images:
    - repository: image.repository
      tag: image.tag
```

Once the image is built I trigger a hook via native webhook. In slack, I see `release update` message but it did not actually update the image(even if it's the same version). Is it possible to achieve this? Always recreate pods with that version on each webhook call.

Thx.
