### ISSUE TITLE
Feature request: default secret ref for the chart

### ISSUE THREAD

**Issue by arthurio** [keel-hq/keel#383]
In the chart, would it be possible to add a `secretRef` to the pod specs, along the lines of:

```yaml
# deployment.yaml
spec:
  ...
  template:
    ...
    spec:
          ...
          envFrom:
            - secretRef:
                name: "{{ .Values.keel.secretName }}"
```

And default it to `keel`? That way it's possible to create a secret file for the third party tokens like slack and if the secret file doesn't exist it will just ignore it.
