### ISSUE TITLE
Duplicated tracked image

### ISSUE THREAD

**Issue by arthurio** [keel-hq/keel#384]
Follow up to a [slack thread](https://kubernetes.slack.com/archives/C6JDWE7M2/p1556965869047600)

1. Provider: helm
2. \# of deployments for the tracked image: 1
3. Keel logs (redacted):

```
"tracked images" images="[
namespace:default,
image:index.docker.io/xxxxxxxxxx/my-image:development-9b315342ea6cdd73c55b315e58f549af612977b7,
provider:helm,
trigger:default,
sched:,
secrets:[]

namespace:default,
image:index.docker.io/xxxxxxxxxx/my-image:development-9b315342ea6cdd73c55b315e58f549af612977b7,
provider:helm,
trigger:default,
sched:,
secrets:[]

namespace:default,
image:index.docker.io/xxxxxxxxxx/my-other-image:development-9b315342ea6cdd73c55b315e58f549af612977b7,
provider:helm,
trigger:default,
sched:,
secrets:[]
]"
```
4. Keel configuration:

```yaml
keel:
  policy: "glob:development-*"
  images:
    - repository: image.repository
      tag: image.tag
      imagePullSecrets:
        - name: regcred
```

5. Deleting/installing keel didn't help
