### ISSUE TITLE
Some bigger updates :) 

### ISSUE THREAD

**Issue by rusenask** [keel-hq/keel#390]
Hey guys,

Lately I have started using Keel in several new projects (automating ML model deployment, increasing number of running services at webhookrelay.com and one more in a way too early stage to talk about). I have noticed that it would be useful to:

- quickly pause/enable updates for deployments without using kubectl. It would be especially useful if multiple services depend on the same image but only a subset of them have to be deployed. 
- expanded API
- authentication - we have recently got basic auth in but it would be nice to expand it in near future and at least start supporting things like github oauth and then potentially add more from there. 
- persistence for approvals. Initially I have added k8s config maps based KV but it proved to be unhappy with permissions quite often and added more problems than anyone would want to deal with.

So, there are few things that I am currently working on:

- sqlite for persistence (easily extended to support postgres, mysql)
- more powerful API, that will allow to:
   * get more information about resources
   * set update policies
   * pause updates
   * set required approvals count
- these API commands are just manipulating k8s resource, so even if you delete and recreate Keel, changes will persist :) 
- audit log - with the database we can now track events that are happening in the cluster so we can see when things were approved, updated and so on.
- UI to actually see and control these all new things: 

![image](https://user-images.githubusercontent.com/9080105/58288794-7dcdd880-7dac-11e9-8e58-29b9a626f2ca.png)

Please note that everything will still going to be primarily configurable through manifest annotations & labels, UI will not be required to do anything that you cannot do through k8s manifests. 

--- 

Also, now that we will have a database where we could put things that can't easily be stored in k8s manifests, we will be able to built on that and do things like:

- https://github.com/keel-hq/keel/issues/369 by creating relationships for certain resources, maybe groups and then approve a group instead of specific resource?
- https://github.com/keel-hq/keel/issues/95 - we can add/retrieve helm repository links in the database
- potentially https://github.com/keel-hq/keel/issues/253 as UI could also benefit of having an endpoint to just set image to specific tag.
- easy rollbacks to previous version. 
- have a database table of "known image tags" so we could suggest which tags user could set. 

--- 

Also, it will soon be ready for testing, if you would want to try out new features & UI, please let me know!

**Comment by theogq** [comment]
I am interested to test the new features. I learned about keel recently and still learning how to use it.

**Comment by rusenask** [comment]
Great, I will try to get it ready for testing and packaged over the weekend. It should be a lot easier with it to get going :)

**Comment by botzill** [comment]
Nice @rusenask! 

I really like it, especially the UI part. Yes, would be nice to have basic auth, right now I'm handling this via ingress, but having it out of the box can be helpful. 

Is there any way to test UI? maybe we can add another section id helm chart and possibility to enable/disable it? 

Thx, looking forward!

**Comment by rusenask** [comment]
UI image is available at `keelhq/keel:ui`

Management APIs & UI will only be available if basic auth details are set for security reasons. To set basic auth, just add env vars:

`BASIC_AUTH_USER` and `BASIC_AUTH_PASSWORD`

```yaml
    spec:
      serviceAccountName: keel
      containers:
        - name: keel
          # Note that we use appVersion to get images tag.
          image: "keelhq/keel:ui"
          imagePullPolicy: Always
          command: ["/bin/keel"]
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            # Enable GCR with pub/sub support
            - name: PROJECT_ID
              value: ""
            # Basic auth (to enable UI/API)
            - name: BASIC_AUTH_USER
              value: "username-x"
            - name: BASIC_AUTH_PASSWORD
              value: "password-xx"
```

It also expects a data volume to be mounted at `/data` but it's only for audit entries and approvals, anything else you do through UI is going to be updating k8s manifests directly so keel deletion won't ruin your config.

This version is only dealing with Kubernetes resources (deployments, daemonsets, statefulsets) and doesn't show Helm releases. I am not sure what to do regarding Helm, their new version just came out and it would be nice to start thinking about just implementing helm v3 rather than continuing to use Tiller :) 

Frontend still needs quite a bit of cleanup and then planning for the next steps, maybe github OAuth would be nice. Btw, it's on `feature/ui` branch if you feel like you want to fix/change anything, wrote it in Vue.js so it's very approachable and simple. 

Good idea regarding switch in Helm for UI, now it's pretty much controlled just by basic auth existence, could it be enough?
