### ISSUE TITLE
Non samver not polling?

### ISSUE THREAD

**Issue by krezh** [keel-hq/keel#395]
I'm not sure if im doing anything wrong as im quite new to kubernetes but it seems that keel isn't doing any polling with non samver tag when using:
```
keel.sh/policy: force
keel.sh/trigger: poll
keel.sh/match-tag: "true"
```

I'm not getting any errors either as seen in the log:
```
time="2019-05-29T00:26:09Z" level=info msg="extension.credentialshelper: helper registered" name=aws 
time="2019-05-29T00:26:09Z" level=info msg="bot: registered" name=slack 
time="2019-05-29T00:26:09Z" level=info msg="keel starting..." arch=amd64 build_date=2019-05-02T165120Z go_version=go1.12 os=linux revision=1c51c706 version=0.14.2 
time="2019-05-29T00:26:09Z" level=info msg="provider.kubernetes: using in-cluster configuration" 
time="2019-05-29T00:26:09Z" level=info msg="provider.helm: tiller address 'tiller-deploy.kube-system.svc.cluster.local:44134' supplied" 
time="2019-05-29T00:26:09Z" level=info msg="provider.defaultProviders: provider 'kubernetes' registered" 
time="2019-05-29T00:26:09Z" level=info msg="provider.defaultProviders: provider 'helm' registered" 
time="2019-05-29T00:26:09Z" level=info msg="extension.credentialshelper: helper registered" name=secrets 
time="2019-05-29T00:26:09Z" level=info msg="bot.slack.Configure(): Slack approval bot is not configured" 
time="2019-05-29T00:26:09Z" level=error msg="bot.Run(): can not get configuration for bot [slack]" 
time="2019-05-29T00:26:09Z" level=info msg="trigger.poll.manager: polling trigger configured" 
time="2019-05-29T00:26:09Z" level=info msg="webhook trigger server starting..." port=9300 
time="2019-05-29T00:26:09Z" level=info msg=started context=watch resource=cronjobs 
time="2019-05-29T00:26:09Z" level=info msg=started context=buffer 
time="2019-05-29T00:26:09Z" level=info msg=started context=watch resource=daemonsets 
time="2019-05-29T00:26:09Z" level=info msg=started context=watch resource=deployments 
time="2019-05-29T00:26:09Z" level=info msg=started context=watch resource=statefulsets 
time="2019-05-29T00:26:13Z" level=info msg="trigger.poll.RepositoryWatcher: new watch repository tags job added" digest="sha256:166d40cc123c9317b304c9afa31d303698855d36cd7ed93b04a9facd442a53f5" image="keelhq/keel:0.14.2" job_name=index.docker.io/keelhq/keel schedule="@every 3m" 
getting:  https://index.docker.io/v2/keelhq/keel/tags/list 
time="2019-05-29T00:26:18Z" level=info msg="trigger.poll.RepositoryWatcher: new watch tag digest job added" digest="sha256:49a76b90e99f9d134c68670d610b5f823f6d4f26aacc22c1d2b31b403bafb75e" image="karolisr/webhook-demo:latest" job_name="index.docker.io/karolisr/webhook-demo:latest" schedule="@every 1m" 
getting:  https://index.docker.io/v2/keelhq/keel/tags/list 
getting:  https://index.docker.io/v2/keelhq/keel/tags/list 
getting:  https://index.docker.io/v2/keelhq/keel/tags/list 
getting:  https://index.docker.io/v2/keelhq/keel/tags/list 

```
The deployment used for testing:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: wd
  namespace: default
  labels: 
      name: "wd"
      keel.sh/policy: force
      keel.sh/trigger: poll
      keel.sh/match-tag: "true"
  annotations:
      keel.sh/pollSchedule: "@every 1m"
spec:
  replicas: 1
  template:
    metadata:
      name: wd
      labels:
        app: wd
    spec:
      containers:
        - image: karolisr/webhook-demo:latest # this would start repository digest checks
          imagePullPolicy: Always
          name: wd
          command: ["/bin/webhook-demo"]
          ports:
            - containerPort: 8090
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8090
            initialDelaySeconds: 30
            timeoutSeconds: 10
```
