### ISSUE TITLE
ECR IAM Role usage

### ISSUE THREAD

**Issue by spaghettifunk** [keel-hq/keel#425]
I tried using the `iam role` in the pod annotation to avoid putting credentials in the `values.yaml` file and push it to GitHub but it seems that keel is not able to pick up the role correctly. 
I was wondering if somebody else managed to make it work with `podsAnnotations` rather than plain credentials. If not, I'll be happy to work on a PR 😃

**Comment by severity1** [comment]
I also want this, based on my tests it seems that even if you set `ecr.enabled: false` this just doesn't set the aws access, secret and region variables and values as seen below.
```
env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POLL
          value: "1"
        - name: HELM_PROVIDER
          value: "1"
        - name: TILLER_NAMESPACE
          value: kube-system
        - name: TILLER_ADDRESS
        - name: BASIC_AUTH_USER
          value: potatoman
        - name: SLACK_CHANNELS
          value: deployment
        - name: SLACK_APPROVALS_CHANNEL
          value: deployment
        - name: SLACK_BOT_NAME
          value: keelbot
        - name: NOTIFICATION_LEVEL
          value: info
```

tried this and keel can still detect that my deployment is using an ECR repo although its giving the usual 401 Not Authorized as seen below.
```
time="2019-08-13T04:48:52Z" level=error msg="trigger.poll.manager: got error(-s) while watching images" error="encountered errors while adding images: Get https://blahblah.dkr.ecr.ap-southeast-2.amazonaws.com/v2/banana/bloop/manifests/0.0.6: http: non-successful response (status=401 body=\"Not Authorized\\n\")"
```

this suggests to me that ecr.enabled just sets variables and values, to me this is a bit misleading. just make `aws.enabled`.

although this also suggests that even if it can still detect that you are using an ecr repo and goes through the ecr logic, something in there explicitly references to the aws key/val to be present.

my expectation is that, if AWS key/val is not present anywhere always fallback to IAM roles/profiles.
