### ISSUE TITLE
Enforce keel policy during initial deployment

### ISSUE THREAD

**Issue by severity1** [keel-hq/keel#428]
First of all, I really like this keel. :)

Given this deployment.yaml;
```
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "floop"
  namespace: operations
  labels:
    name: "floop"
    keel.sh/policy: all
    keel.sh/trigger: poll
    keel.sh/approvals: "3"
    keel.sh/approvalDeadline: "24h"
  annotations:
    keel.sh/pollSchedule: "@every 1m"
spec:
  selector:
    matchLabels:
      app: "floop"
  replicas: 1
  template:
    metadata:
      name: "floop"
      namespace: operations
      labels:
        app: "2048"
        component: frontend
   spec:
      containers:
      - name: "floop"
        image: someacct.dkr.ecr.ap-southeast-2.amazonaws.com/banana/floop:0.0.6
        imagePullPolicy: Always
        ports:
        - containerPort: 80
```

upon initial apply it will always deploy version/tag `0.0.6` and then it will wait for 1minute before it applies the version/tag enforced by keel policy. `0.0.6 -> 0.0.8`.

This scenario momentarily leaves your deployment in a bad state. It becomes far worse if your pollSchedule is longer because this means initial deployment will be in a bad state for a longer period of time.

i propose that initial deployments should apply the version/tag enforced by keel policy.

As long as "desired state" can be enforced using `keel.sh/policy:` i don't think we will need flux style gitops.

Of course i can always just rely on editing version/tag directly on this deployment.yaml file but that defeats the purpose of keel policy.
