### ISSUE TITLE
Keel Basic Auth with Helm Chart 404's without basic auth

### ISSUE THREAD

**Issue by jakesyl** [keel-hq/keel#502]
If I deploy without basic auth enabled, my main page looks like this:

![image](https://user-images.githubusercontent.com/6392429/83658384-24d47b00-a590-11ea-97d8-2fcf75226145.png)

Here's the helm chart:

```
# See https://github.com/keel-hq/keel/tree/d6ba949e6e3c6a5d72f35c40e52b14783f70e5c5/chart/keel
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: type
          operator: In
          values:
          - [hidden]
  podAffinity:

service:
  enabled: true
  type: LoadBalancer
  externalPort: 9300
  internalPort: 9300

gcr:
  enabled: true
  projectId: [hidden]
  pubsub:
    enabled: true

webhook:
  enabled: true
  endpoint: [hidden]

#basicauth:
#   enabled: false
#   user: admin
#   password: [hidden]

secret:
  name: [hidden]
  create: true

helmProvider:
  enabled: false

insecureRegistry: true
googleApplicationCredentials: [hidden]

ingress:
  enabled: true
  hosts:
   - host: [hidden]
     paths:
       - /
  tls:
    - secretName: [hidden]
      hosts:
        - "[hidden]"
```

This is version 0.8.22 of helm. If I turn basic on auth so:

```
# See https://github.com/keel-hq/keel/tree/d6ba949e6e3c6a5d72f35c40e52b14783f70e5c5/chart/keel
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: type
          operator: In
          values:
          - [hidden]
  podAffinity:

service:
  enabled: true
  type: LoadBalancer
  externalPort: 9300
  internalPort: 9300

gcr:
  enabled: true
  projectId: [hidden]
  pubsub:
    enabled: true

webhook:
  enabled: true
  endpoint: [hidden]

basicauth:
  enabled: true
  user: admin
  password: [hidden]

secret:
  name: [hidden]
  create: true

helmProvider:
  enabled: false

insecureRegistry: true
googleApplicationCredentials: [hidden]

ingress:
  enabled: true
  hosts:
   - host: [hidden]
     paths:
       - /
  tls:
    - secretName: [hidden]
      hosts:
        - "[hidden]"
```

Everything works fine
