### ISSUE TITLE
0.17.0-rc1 level=fatal msg="failed to setup Tiller tunnel" error="could not find tiller"

### ISSUE THREAD

**Issue by rreilly-edr** [keel-hq/keel#518]
Deploy the rc this am, default chart except i am setting basic auth and setting tag to "0.17.0-rc1"

helm version 3.2.4
keel 0.17.0-rc1
k8s v1.15.11-eks-af3caf

```
image:
  repository: keelhq/keel
  tag: 0.17.0-rc1
  pullPolicy: Always

# Enable insecure registries
insecureRegistry: false

# Polling is enabled by default,
# you can disable it setting value below to false
polling:
  enabled: true

# Helm provider support
helmProvider:
  version: "v3"
  enabled: true
```

Log from pod

```
time="2020-07-14T12:05:15Z" level=info msg="extension.credentialshelper: helper registered" name=aws
time="2020-07-14T12:05:15Z" level=info msg="extension.credentialshelper: helper registered" name=gcr
time="2020-07-14T12:05:15Z" level=info msg="bot: registered" name=slack
time="2020-07-14T12:05:15Z" level=info msg="keel starting..." arch=amd64 build_date=2020-07-14T093948Z go_version=go1.14.2 os=linux revision=36bbafc4 version=0.17.0-rc1
time="2020-07-14T12:05:15Z" level=info msg="initializing database" database_path=/data/keel.db type=sqlite3
time="2020-07-14T12:05:15Z" level=info msg="extension.notification.auditor: audit logger configured" name=auditor
time="2020-07-14T12:05:15Z" level=info msg="notificationSender: sender configured" sender name=auditor
time="2020-07-14T12:05:15Z" level=info msg="provider.kubernetes: using in-cluster configuration"
time="2020-07-14T12:05:15Z" level=fatal msg="failed to setup Tiller tunnel" error="could not find tiller"
```
