### ISSUE TITLE
https://charts.keel.sh/index.yaml - connection refused

### ISSUE THREAD

**Issue by aleksey005** [keel-hq/keel#521]
`Error in HTTP GET to [https://charts.keel.sh/index.yaml], error: Get https://charts.keel.sh/index.yaml: dial tcp 104.27.165.119:443: connect: connection refused`

**Comment by rusenask** [comment]
It's on GCP storage, could there be some network/firewall issue on your side?

```
curl https://charts.keel.sh/index.yaml
apiVersion: v1
entries:
  keel:
  - apiVersion: v1
    appVersion: 0.16.1
    created: "2020-07-14T09:34:48.284701875Z"
    description: Open source, tool for automating Kubernetes deployment updates. Keel
      is stateless, robust and lightweight.
    digest: 17ea4145520080ce642e8f60a2f04c81e93ae6e4ff94f37301159936da95b27a
    engine: gotpl
    home: https://keel.sh
    icon: https://raw.githubusercontent.com/keel-hq/keel/master/static/keel-logo.png
    keywords:
    - kubernetes deployment
    - helm release

```
