### ISSUE TITLE
Keel updates deployments all the time

### ISSUE THREAD

**Issue by TXZdream** [keel-hq/keel#536]
I use keel to auto-upgrade my project, conf file like this:
```
labels:
  keel.sh/policy: all
  keel.sh/trigger: poll
annotations:
  keel.sh/policy: "glob:*-dev"
```
The image has image with dev, latest, 2.6.2, 1.0.1-dev, currently the image version is 1.0.1-dev, I expected that keel will not update because there is no tag with given policy larger that 1.0.1-dev. But I found the deployment always delete and redeploy pods with the same version.
Is that a bug? Or there is some reason for that?
