### ISSUE TITLE
Slack's approval system seems to be unresponsive

### ISSUE THREAD

**Issue by hjpotter92** [keel-hq/keel#552]
I have gone through #349 and #362. I have configured keel using following configurations:

``` yaml
- name: AUTHENTICATED_WEBHOOKS
  value: "false"
- name: SLACK_BOT_NAME
  value: "keel"
- name: SLACK_CHANNELS
  value: "keel-updates"
- name: SLACK_APPROVALS_CHANNEL
  value: "keel-approvals"
- name: NOTIFICATION_LEVEL
  value: "debug"
```

I configured the app/bot using the link provided [in docs](https://keel.sh/docs/#configuring-approvals-with-slack) (URL: `https://[organisation].slack.com/apps/A0F7YS25R-bots`).

![image](https://user-images.githubusercontent.com/3393533/95750290-8cc36c80-0cba-11eb-8be4-8fbb926743f3.png)

I setup a policy for one of the deployments in my kubernetes cluster. I do receive approval request notification in slack channel:

![image](https://user-images.githubusercontent.com/3393533/95750442-c8f6cd00-0cba-11eb-9d9e-6fcf81fbec1e.png)

As can be seen in the screenshots above, the notifications for approvals do arrive to the channel, however the approvals system does not.

Any help/pointers would be appreciated.

**Comment by GijsvanDulmen** [comment]
Did you also setup the incoming side of things and therefore provide a SLACK_TOKEN env var to the keel deployment?

**Comment by hjpotter92** [comment]
Yes, @GijsvanDulmen . Slack token is loaded via a kubernetes opaque secret manifest:

``` yaml

apiVersion: v1
data:
  SLACK_TOKEN: <base-64 encoded app token>
  BASIC_AUTH_USER: a2VlbGFkbWlu
  BASIC_AUTH_PASSWORD: UGEkJDF3b3Jk
kind: Secret
metadata:
  name: keel-secrets
type: Opaque
---
```
