### ISSUE TITLE
trigger.poll.RepositoryWatcher: image no tracked anymore, removing watcher

### ISSUE THREAD

**Issue by fbrv** [keel-hq/keel#561]
Hi,
I'm making some experiments with keel and I have the following issue. Whenever I push a new image to the ECR registry the image is not updated.  
my deployment file:  
```
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: development
  name: api-gateway
  labels:
    app: api-gateway
    keel.sh/policy: force
    keel.sh/trigger: poll    
  annotations:
    keel.sh/policy: "glob:next-*"
    keel.sh/pollSchedule: "@every 1m"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: <aws-id>.dkr.ecr.eu-west-2.amazonaws.com/api-gateway:next-v16-468a6827e20d686fd2ff6a2ff0966d1860740a0c
        ports:
        - name: gateway-port
          containerPort: 8080
        imagePullPolicy: Always
```
The complete log is the following:
```
time="2020-11-23T12:06:00Z" level=info msg="extension.credentialshelper: helper registered" name=aws
time="2020-11-23T12:06:00Z" level=info msg="extension.credentialshelper: helper registered" name=gcr
time="2020-11-23T12:06:00Z" level=info msg="bot: registered" name=slack
time="2020-11-23T12:06:00Z" level=info msg="keel starting..." arch=amd64 build_date=2020-06-07T155004Z go_version=go1.14.2 os=linux revision=82ba1d50 version=0.16.1
time="2020-11-23T12:06:00Z" level=info msg="initializing database" database_path=/data/keel.db type=sqlite3
time="2020-11-23T12:06:00Z" level=info msg="extension.notification.auditor: audit logger configured" name=auditor
time="2020-11-23T12:06:00Z" level=info msg="notificationSender: sender configured" sender name=auditor
time="2020-11-23T12:06:00Z" level=info msg="provider.kubernetes: using in-cluster configuration"
time="2020-11-23T12:06:00Z" level=info msg="provider.defaultProviders: provider 'kubernetes' registered"
time="2020-11-23T12:06:00Z" level=info msg="extension.credentialshelper: helper registered" name=secrets
time="2020-11-23T12:06:00Z" level=info msg="bot.slack.Configure(): Slack approval bot is not configured"
time="2020-11-23T12:06:00Z" level=error msg="bot.Run(): can not get configuration for bot [slack]"
time="2020-11-23T12:06:00Z" level=info msg="authentication is not enabled, admin HTTP handlers are not initialized"
time="2020-11-23T12:06:00Z" level=info msg="webhook trigger server starting..." port=9300
time="2020-11-23T12:06:00Z" level=info msg="trigger.poll.manager: polling trigger configured"
time="2020-11-23T12:06:00Z" level=info msg=started context=watch resource=statefulsets
time="2020-11-23T12:06:00Z" level=info msg=started context=buffer
time="2020-11-23T12:06:00Z" level=info msg=started context=watch resource=deployments
time="2020-11-23T12:06:00Z" level=info msg=started context=watch resource=daemonsets
time="2020-11-23T12:06:00Z" level=info msg=started context=watch resource=cronjobs
time="2020-11-23T12:06:42Z" level=info msg="trigger.poll.RepositoryWatcher: new watch tag digest job added" digest="sha256:8922dd3d49f68b61f6131da5c4812d5b86b0db98072b78ed1d540f3350a66f47" image="api-gateway:next-v16-468a6827e20d686fd2ff6a2ff0966d1860740a0c" job_name="<aws-id>.dkr.ecr.eu-west-2.amazonaws.com/api-gateway:next-v16-468a6827e20d686fd2ff6a2ff0966d1860740a0c" schedule="@every 1m"
time="2020-11-23T12:11:06Z" level=info msg="trigger.poll.RepositoryWatcher: image no tracked anymore, removing watcher" image="namespace:development,image:<aws-id>.dkr.ecr.eu-west-2.amazonaws.com/api-gateway:next-v16-468a6827e20d686fd2ff6a2ff0966d1860740a0c,provider:kubernetes,trigger:poll,sched:@every 1m,secrets:[]" job_name="<aws-id>.dkr.ecr.eu-west-2.amazonaws.com/api-gateway:next-v16-468a6827e20d686fd2ff6a2ff0966d1860740a0c" schedule="@every 1m"
```
I have deployed keel using helm and disabled helm and enabled ecr, using a values file (the user has the correct credentials for both ec2 and ecr).
Whenever I update an image inside the registry keel is not updating the image and after a while I get the log
```
trigger.poll.RepositoryWatcher: image no tracked anymore, removing watcher
```
What am I doing wrong?
