### ISSUE TITLE
Unable to restrict keel to specific namespace

### ISSUE THREAD

**Issue by sasanknvs** [keel-hq/keel#565]
With the default set up keel monitors all the objects in all the namespaces. But I want to restrict that to a specific namespace. I tried to restrict by changing the Clusterrole and clusterrolebinding to Role and Rolebinding, but when modified this it is not showing anything in the admin dashboard.

Can you anyone help out with this ?

**Comment by nbendafi-yseop** [comment]
@sasanknvs There is actually no _filtering_ done in Keel regarding which namespace to watch for `Deployments`, `Daemonsets` and so on.

As you guessed, one should indeed rely on [Using RBAC Authorization](https://kubernetes.io/docs/reference/access-authn-authz/rbac).

From what you said, I suspect that your are missing something, in between. You cannot _just_ move both `Clusterrole` (resp.`ClusterRoleBinding`) to `Role` (resp. `RoleBinding`) as-is.
In order for Keel (or any other component) to list _namespaced_ resources (with relevant `Role` and `RoleBinding`) it still needs to have _access_ to `namespaces` resources, so I suggest you to still keep
```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keel
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keel
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keel
subjects:
  - kind: ServiceAccount
    name: keel
    namespace: keel
```
