### ISSUE TITLE
keel deployed with helm runs as cluster-admin

### ISSUE THREAD

**Issue by ghouscht** [keel-hq/keel#571]
Hi,
I found that keel deployed through helm runs as cluster-admin which is bad. The cluster-admin group has way to many permissions than actually needed by keel.

I used this command to see the rendered deployment
```bash
helm template keel keel/keel --namespace kube-keel --set helmProvider.version="v3"
```

The output contains a ServiceAccount and a ClusterRole named `keel`, but the ClusterRoleBinding does not refer to this cluster role and instead uses the ClusterRole `cluster-admin`:

Relevant part of the rendered helm chart:
```yaml
---
# Source: keel/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
# apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: keel
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  # name: keel
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: keel
    namespace: kube-keel

```

Source of this can be seen here: https://github.com/keel-hq/keel/blob/aa4a9f7fd786146dbcc4b8a79fffcd9af4213a6a/chart/keel/templates/clusterrolebinding.yaml#L10-L11

I think this can be considered a security relevant bug and makes the helm chart unusable for me! I can send a PR to fix this if you like.
Cheers, 
Thomas
