### ISSUE TITLE
Fix request: deployment.yaml error when Google Application Credentials is active and persistence is also

### ISSUE THREAD

**Issue by ivanilsonaraujojr** [keel-hq/keel#589]
```shell
Release "keel" does not exist. Installing it now.
Error: release keel failed: Deployment.apps "keel" is invalid: spec.template.spec.containers[0].volumeMounts[0].name: Not found: "storage-logs"
```
values.yaml

```yaml
googleApplicationCredentials: dGVzdHRlc3R0ZXN0MTIzMzI1NjQ5NTcxMjM1Ngo=

persistence:
  enabled: true
  storageClass: "standard"
```

chart/keel/templates/deployment.yaml
```yaml
{{- if .Values.persistence.enabled }}
      volumes:
        - name: storage-logs
          persistentVolumeClaim:
            claimName: {{ template "keel.fullname" . }}
{{- end }}
[...]
{{- if .Values.googleApplicationCredentials }}
      volumes:
        - name: secret
          secret:
            secretName: {{ .Values.secret.name | default (include "keel.fullname" .) }}
{{- end }}
```

## _fix_: #588
