### ISSUE TITLE
WEBHOOK_URL pointing to an cluster service svc.cluster.local fail

### ISSUE THREAD

**Issue by zaggash** [keel-hq/keel#598]
**Keel**: 0.16.1  
**WEBHOOK_URL** configured to reach an internal service:  `http://myservice.namespace.svc.cluster.local:5000  `

The logs reports failed to send the notification message with:  
```
 Could not dial broker: dial tcp: lookup myservice.namespace.svc.cluster.local device or resource busy
```

However, if I set the same webhook service as a sidecar along with keel, and `WEBHOOK_URL=http://127.0.0.1:5000`, it works like a charm.

Could it be possible the issue below is related?
https://github.com/segmentio/kafka-go/issues/285
https://github.com/golang/go/issues/35067

**Comment by boomfly** [comment]
This is alpine issue.
I found workaround.
Add these to keel deployment:

```yaml
command: ['/bin/sh', '-c', 'apk add bind-tools && /bin/keel']

env:
- name: GODEBUG
   value: netdns=go

dnsConfig:
  options:
  - name: ndots
    value: '2'
```

**bind-tools**: [stackoverflow](https://stackoverflow.com/questions/65181012/does-alpine-have-known-dns-issue-within-kubernetes)
