### ISSUE TITLE
Additional permissions are needed to allow use with PodSecurityPolicies

### ISSUE THREAD

**Issue by djschaap** [keel-hq/keel#599]
Commit 1bb67d1 (keel chart 0.9.6) modified the keel ServiceAccount to use a dedicated ClusterRole instead of cluster-admin.  This ClusterRole, defined in `chart/keel/templates/clusterrole.yaml`, requires additional permissions.

To allow keel to monitor AWS ECR repositories, I had to grant `create` and `update` verbs on the `secrets` resource.

To allow keel to actually update the image in my Deployment, I had to grant `get` on the `serviceaccounts` and `services` resources.
```
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
      - services
    verbs:
      - get
```

This behavior was seen under Kubernetes 1.20.2 with the `latest` keel image installed via chart 0.9.8, using the helm3 provider.  I was updating a very simple Helm Release (deployment, service, serviceaccount templates) - additional permissions MAY be required if other resource types are included in the Release.
