### ISSUE TITLE
Missing startupProbe from Deployment

### ISSUE THREAD

**Issue by exxbrain** [keel-hq/keel#605]
I can not find startupProbe in Deployment after Deployment update. This is the values:

```yml
helmProvider:
  version: "v3"

service:
  enabled: true
  
debug: true
 
ingress: 
  enabled: true
  hosts: 
    - 
      host: "keel.test.one"
      paths: 
        - /
```
