### ISSUE TITLE
Keel pod status "Error" when applying deployment

### ISSUE THREAD

**Issue by bensch98** [keel-hq/keel#622]
I'm new to Keel and tried deploying it via helm (v3). However my keel pod only runs as long as I have no Deployment running with keel annotations. Otherwise the keel pod crashes. I guess I missed some installation steps or my deployment file is horribly wrong. I've tried to summarize all relevant information. If anything is missing, let me know. Thankful for any help!

Steps I did:

**Installing helm** (did not use it before)

```bash
curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
sudo apt-get install apt-transport-https --yes
echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
sudo apt-get update
sudo apt-get install helm
```

**Helm version**:

```text
version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"clean", GoVersion:"go1.16.3"}
```

**Installing keel**:

```bash
helm repo add keel https://charts.keel.sh 
helm repo update
helm install keel keel/keel --set helmProvider.version="v3" 
```

My example deployment which causes the keel pod to crash:
The mistake lays not in the image, as the deployment works just fine without the keel annotations. The Deployment works well when I only write `keel.sh/policy: all` but still does not update anything when I push new images to my docker hub.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
spec:
  selector:
    matchLabels:
      run: nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: nginx
    spec: 
      hostNetwork: true
      containers:
      - name: nginx
        image: bensch98/nginx-test:0.0.1
        imagePullPolicy: Always
```

I did not quite understand if it is necessary to setup webhooks. Nevertheless I tried it with following steps:
I created the RELAY_KEY and RELAY_SECRET over [my-webhooks](https://my.webhookrelay.com/tokens) as proposed in the official documentation.

```bash
helm repo add webhookrelay https://charts.webhookrelay.com
helm repo update

export RELAY_KEY=*****-****-****-****-*********
export RELAY_SECRET=**********

helm upgrade --install webhookrelay-operator webhookrelay/webhookrelay-operator \
  --set credentials.key=$RELAY_KEY --set credentials.secret=$RELAY_SECRET

kubectl apply -f webhookrelay_cr.yaml
```

<details>
<summary><i>webhook_cr.yaml</i></summary>

```yaml
# webhookrelay_cr.yaml
apiVersion: forward.webhookrelay.com/v1
kind: WebhookRelayForward
metadata:
  name: keel-forward
spec:
  buckets:
  - name: dockerhub-to-keel
    inputs:
    - name: dockerhub-endpoint
      description: "Public endpoint"
      responseBody: "OK"
      responseStatusCode: 200
    outputs:
    - name: keel
      destination: http://keel:9300/v1/webhooks/dockerhub
      internal: true
```
</details>

<details>
<summary><i>kubectl get pods -o wide</i></summary>

```text
NAME                                              READY   STATUS    RESTARTS   AGE     IP              NODE    NOMINATED NODE   READINESS GATES
keel-855d5498f8-jp7qj                             1/1     Running   3          90m     192.168.38.72   mypc    <none>           <none>
keel-forward-whr-deployment-59cfcd47b5-vdwvf      1/1     Running   0          5m27s   192.168.38.79   mypc    <none>           <none>
webhookrelay-operator-75d755c6d-x42rd             1/1     Running   0          42m     192.168.38.75   mypc    <none>           <none>
```

</details>

Although the webhookrelay-operator and the keel-forward pod is running I don't get a Public Endpoint, as described in the documentation. As of my understandingI have to create in e.g. Dockerhub a webhook with the here specified public endpoint.
<details>
<summary><i>kubectl describe webhookrelayforwards.forward.webhookrelay.com keel-forward</i></summary>

```text
Name:         keel-forward
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  forward.webhookrelay.com/v1
Kind:         WebhookRelayForward
Metadata:
  Creation Timestamp:  2021-06-15T23:05:18Z
  Generation:          1
  Managed Fields:
    API Version:  forward.webhookrelay.com/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:buckets:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2021-06-15T23:05:18Z
    API Version:  forward.webhookrelay.com/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:agentStatus:
        f:message:
        f:ready:
        f:routingStatus:
    Manager:         webhookrelay-operator
    Operation:       Update
    Time:            2021-06-15T23:07:15Z
  Resource Version:  50879
  Self Link:         /apis/forward.webhookrelay.com/v1/namespaces/default/webhookrelayforwards/keel-forward
  UID:               6aeb5ca1-a01b-4386-a4f6-e32cdb3bb36c
Spec:
  Buckets:
    Inputs:
      Description:           Public endpoint
      Name:                  dockerhub-endpoint
      Response Body:         OK
      Response Status Code:  200
    Name:                    dockerhub-to-keel
    Outputs:
      Destination:  http://keel:9300/v1/webhooks/dockerhub
      Internal:     true
      Name:         keel
Status:
  Agent Status:    Running
  Message:         encountered errors (failed to list buckets, error: error from makeRequest: HTTP request failed: Get "https://my.webhookrelay.com/v1/buckets": dial tcp: lookup my.webhookrelay.com on 10.96.0.10:53: server misbehaving) while ensuring routing configuration, check your CR spec
  Ready:           true
  Routing Status:  Failed
Events:            <none>
```
</details>
