### ISSUE TITLE
Image not updated after pushed to Docker Hub

### ISSUE THREAD

**Issue by bensch98** [keel-hq/keel#624]
I'm running a Kubernetes Cluster (version: 1.19.12) locally on my PC and installed keel via helm (version 3.5) with following steps:

```bash
helm repo add keel https://charts.keel.sh
helm repo update
helm install keel keel/keel --set helmProvider.version="v3"
```
The keel pod is now running along with an nginx example deployment.

```text
NAME                    READY   STATUS    RESTARTS   AGE
keel-855d5498f8-cp9fd   1/1     Running   0          47m
nginx-97c944f68-z6fft   1/1     Running   0          54m
```

My Deployment looks like this:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
  annotations:
    keel.sh/policy: all
    #keel.sh/trigger: poll
    #keel.sh/pollSchedule: "@every 30s"
spec:
  selector:
    matchLabels:
      run: nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: nginx
    spec: 
      hostNetwork: true
      containers:
      - name: nginx
        image: bensch98/nginx-test:latest
        imagePullPolicy: Always
```

If I uncomment and apply this:
```text
#keel.sh/trigger: poll
#keel.sh/pollSchedule: "@every 30s"
```
the pod crashes can not restart. But even when the pod is running and I push a new image to my repo with tag `:latest` (or any other tag) the pod is not being restarted. What am I missing, or does keel not support helm v3? [Issue #567](https://github.com/keel-hq/keel/issues/567) seems to describe the same or a similar bug. Is there a solution to this?

The keel-pod logs look like this:
kubectl logs keel-855d5498f8-cp9fd

```text
time="2021-06-19T19:42:56Z" level=info msg="extension.credentialshelper: helper registered" name=aws
time="2021-06-19T19:42:56Z" level=info msg="extension.credentialshelper: helper registered" name=gcr
time="2021-06-19T19:42:56Z" level=info msg="bot: registered" name=slack
time="2021-06-19T19:42:56Z" level=info msg="keel starting..." arch=amd64 build_date=2020-06-07T155004Z go_version=go1.14.2 os=linux revision=82ba1d50 version=0.16.1
time="2021-06-19T19:42:56Z" level=info msg="initializing database" database_path=/data/keel.db type=sqlite3
time="2021-06-19T19:42:56Z" level=info msg="extension.notification.auditor: audit logger configured" name=auditor
time="2021-06-19T19:42:56Z" level=info msg="notificationSender: sender configured" sender name=auditor
time="2021-06-19T19:42:56Z" level=info msg="provider.kubernetes: using in-cluster configuration"
time="2021-06-19T19:42:56Z" level=info msg="provider.defaultProviders: provider 'kubernetes' registered"
time="2021-06-19T19:42:56Z" level=info msg="extension.credentialshelper: helper registered" name=secrets
time="2021-06-19T19:42:56Z" level=info msg="bot.slack.Configure(): Slack approval bot is not configured"
time="2021-06-19T19:42:56Z" level=error msg="bot.Run(): can not get configuration for bot [slack]"
time="2021-06-19T19:42:56Z" level=info msg="trigger.poll.manager: polling trigger configured"
time="2021-06-19T19:42:56Z" level=info msg=started context=watch resource=statefulsets
time="2021-06-19T19:42:56Z" level=info msg=started context=watch resource=daemonsets
time="2021-06-19T19:42:56Z" level=info msg=started context=watch resource=deployments
time="2021-06-19T19:42:56Z" level=info msg="authentication is not enabled, admin HTTP handlers are not initialized"
time="2021-06-19T19:42:56Z" level=info msg="webhook trigger server starting..." port=9300
time="2021-06-19T19:42:56Z" level=info msg=started context=buffer
time="2021-06-19T19:42:56Z" level=info msg=started context=watch resource=cronjobs
```
