### ISSUE TITLE
Helm V3 Image Update doesn't work

### ISSUE THREAD

**Issue by derjohn** [keel-hq/keel#626]
Hello,
I installed keel like this:
```
helm upgrade --install keel --namespace=kube-system keel/keel --set helmProvider.version=v3 --set helmProvider.enabled=true --set image.tag=latest --set basicauth.enabled=true --set basicauth.user=xxx --set basicauth.password=xxx --set debug=false
```

And added this to my deployment's values.yaml:
```
keel:
  policy: "glob:miner-amd64_validator*"
  #  or: policy: "regexp:^miner-amd64_validator.*$"
  trigger: poll
  pollSchedule: "@every 2m"
  images:
    - repository: image.repository
      tag: image.tag
...
image:
  pullPolicy: IfNotPresent
  repository: quay.io/team-helium/validator
  tag: miner-amd64_validator1.0.2

```
 
I see in the keel pod log:
time="2021-06-30T11:11:52Z" level=info msg="trigger.poll.RepositoryWatcher: new watch tag digest job added" digest="sha256:08eff279bd21ff23256e94ac4b8ddf404d29c3df05186002fb9b54981333d0a9" image="team-helium/validator:miner-amd64_validator1.0.2" job_name="quay.io/team-helium/validator:miner-amd64_validator1.0.2" schedule="@every 3m"

But nothing more happens, even if quay.io/team-helium/validator:miner-amd64_validator1.0.3 is already in the repo.

Is the helm3 thingy supposed to work with "non-latest" and glob or regexp policy?

rgds,
j.
