### ISSUE TITLE
Problem updating helm chart

### ISSUE THREAD

**Issue by Infray** [keel-hq/keel#628]
Hi
I've installed keel on my k3s cluster( v1.21.0-k3s1) using the helm chart with default values except for:
```
image:
  repository: keelhq/keel
  tag: latest
...
helmProvider:
  enabled: true
  # set to version "v3" for Helm v3
  version: v3
...
# Keel service
# Enable to receive webhooks from Docker registries
service:
  enabled: true
  type: ClusterIP
  externalPort: 9300
...
keel:
  images:
    - repository: image.repository
      tag: image.tag
  policy: all
  pollSchedule: "@hourly"
  trigger: poll
```

I've been installing helm charts using bitnami's kubeapps for a while now and this seems to work fine.
However when I try to use keel to update an image I get following error:

`time="2021-07-16T20:12:50Z" level=fatal msg="helm3: failed to update release from chart" error="template: komga/templates/common.yaml:1:3: executing \"komga/templates/common.yaml\" at <include \"common.all\" .>: error calling include: template: no template \"common.all\" associated with template \"gotpl\""`

This is in reference to the komga helm chart from k8s-at-home.

I've added following to the previously deployed chart:
keel:
  images:
  - repository: image.repository
    tag: image.tag
  policy: all
  pollSchedule: '@every 2m'
  trigger: poll

Any reason why this fails on the subchart?

Kind Regards

**Comment by grewhit25** [comment]
I had this problem sometime back;  [issue](https://github.com/nicholaswilde/helm-charts/issues/3). The problem is related to Charts that are build using the ‘Common’ library.

You can resolve the issue by adding the following to your values.yaml

```yaml
# values.yaml
---
controllerAnnotations:
  keel.sh/pollSchedule: "@every 10m"

controllerLabels:
  keel.sh/policy: all
  keel.sh/trigger: poll
```

Hope that helps.
