### ISSUE TITLE
pollSchedule can't use second unit

### ISSUE THREAD

**Issue by winds6206** [keel-hq/keel#663]
Hi

I wanna my service can poll GCR every 30s, I set annatation like this
```
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 30s"
    keel.sh/approvals: "1"
```

but it's not work.

then I try to set it to minutes
```
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 1m"
    keel.sh/approvals: "1"
```
It's working

Is this a bug@@?
