### ISSUE TITLE
Add securityContext and non-root user

### ISSUE THREAD

**Issue by joebowbeer** [keel-hq/keel#679]
# Summary

Add `securityContext` to the keel Deployment so that it complies with PSS/restricted:

https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted

# Motivation

The default install fails 4 of the policies:

```bash
kustomize build https://github.com/kyverno/policies//pod-security | \
  kyverno apply --policy-report -r \
  <(helm template --repo https://charts.keel.sh keel) \
  -
```

The 4 failures are because a `securityContext` with 4 required properties is missing from the keel Deployment:

```yaml
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
```

# Proposal

Adding a securityContext with three of the properties should be trivial.

Adding `runAsNonRoot` will require more work because the `keelhg/keel` image currently runs as root. This can be addressed by adding a non-root USER with numeric id to the Dockerfile.
