### ISSUE TITLE
Image Pull Secrets not being used, Incorrect registry type

### ISSUE THREAD

**Issue by chrismith-equinix** [keel-hq/keel#683]
Hi there,

I'm trying to run Keel in my Rancher cluster, deployed using Kubernetes manifests, and am facing 2 issues. The startup debug log is at the bottom of this post. All images that I would like to poll are all tagged with semver.

Some info about my environment:

```
Rancher version: 2.5.6
Kubernetes version: 1.17.17
Kubectl version: 1.24.1
Registry type: JFrog Artifactory 
```

**First issue:** The Image Pull Secrets are not being used

Other workloads are using the same `imagePullSecret` and can pull images without issue. I have also tried configuring the `imagePullSecret` in the Keel Deployment itself, and get the same result.

**Second issue:** The Image Pull Secrets are not being used

I'm not quite sure what these log lines are actually telling me, but it seems that AWS ECR is the default registry(i.e. "helper=aws"). 

```
time="2022-07-21T14:23:09Z" level=debug msg="extension.credentialshelper: helper doesn't support this registry" error="unsupported registry" helper=aws tracked_image="namespace:mynamespace,image:myregistry/app1:1.0.29,provider:kubernetes,trigger:poll,sched:@every 10s,secrets:[]"
time="2022-07-21T14:23:09Z" level=debug msg="extension.credentialshelper: credentials helper not found" tracked_image="namespace:mynamespace,image:myregistry/app1:1.0.29,provider:kubernetes,trigger:poll,sched:@every 10s,secrets:[]"
```

**Questions:**

**1. Are there any workarounds to configure the Keel Deployment to use the `imagePullSecrets` specified in the Keel `ServiceAccount`?
2. How can I tell the Keel deployment that my registry type is Artifactory, not AWS?**

Any help here would be appreciated!

Here is the keel `ServiceAccount` yaml, with `imagePullSecret` configured, and other Kubernetes manifests being used to deploy Keel.

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keel
  namespace: mynamespace
  labels:
    app: keel
imagePullSecrets: 
- name: mysecret
```
Here is the ClusterRoleBinding being used. 

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keel
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keel
subjects:
  - kind: ServiceAccount
    name: keel
    namespace: mynamespace
```
Here is the Keel `Deployment` ... all other Keel resources being used are unchanged from the template at: [deployment-template.yaml](https://github.com/keel-hq/keel/blob/master/deployment/deployment-template.yaml)

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keel
  namespace: mynamespace
  labels:
    app: keel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keel
  template:
    metadata:
      labels:
        app: keel
    spec:
      serviceAccountName: keel
      containers:
      - name: keel
        image: "keelhq/keel:latest"
        imagePullPolicy: Always
        command: ["/bin/keel"]
        env:
          - name: NAMESPACE
            value: "mynamespace"
          - name: DEBUG
            value: "true"
        ports:
        - containerPort: 9300
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9300
          initialDelaySeconds: 30
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
```

Here is the `Deployment` for the service I would like to poll, configured with Keel annotations.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: mynamespace
  labels:
    app: app1
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 10s"
    keel.sh/approvals: "0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      serviceAccountName: myserviceaccount
      containers:
      - name: app1
        image: myregistry/app1:1.0.29
        imagePullPolicy: Always
        ports:
        - containerPort: 1234
```

**Startup log**

```
time="2022-07-21T14:23:06Z" level=info msg="extension.credentialshelper: helper registered" name=aws
time="2022-07-21T14:23:06Z" level=info msg="extension.credentialshelper: helper registered" name=gcr
time="2022-07-21T14:23:06Z" level=info msg="bot: registered" name=slack
time="2022-07-21T14:23:06Z" level=info msg="keel starting..." arch=amd64 build_date=2021-11-03T100444Z go_version=go1.14.2 os=linux revision=74a5f3b0 version=
time="2022-07-21T14:23:06Z" level=info msg="initializing database" database_path=/data/keel.db type=sqlite3
time="2022-07-21T14:23:06Z" level=debug msg="extension.notification: sender registered" name=auditor
time="2022-07-21T14:23:06Z" level=info msg="extension.notification.auditor: audit logger configured" name=auditor
time="2022-07-21T14:23:06Z" level=info msg="notificationSender: sender configured" sender name=auditor
time="2022-07-21T14:23:06Z" level=info msg="provider.kubernetes: using in-cluster configuration"
time="2022-07-21T14:23:06Z" level=info msg="provider.defaultProviders: provider 'kubernetes' registered"
time="2022-07-21T14:23:06Z" level=info msg="extension.credentialshelper: helper registered" name=secrets
time="2022-07-21T14:23:06Z" level=info msg="bot.slack.Configure(): Slack approval bot is not configured"
time="2022-07-21T14:23:06Z" level=error msg="bot.Run(): can not get configuration for bot [slack]"
time="2022-07-21T14:23:06Z" level=info msg="trigger.poll.manager: polling trigger configured"
time="2022-07-21T14:23:06Z" level=info msg=started context=watch resource=statefulsets
time="2022-07-21T14:23:06Z" level=info msg="authentication is not enabled, admin HTTP handlers are not initialized"
time="2022-07-21T14:23:06Z" level=info msg="webhook trigger server starting..." port=9300
time="2022-07-21T14:23:06Z" level=info msg=started context=watch resource=deployments
time="2022-07-21T14:23:06Z" level=info msg=started context=buffer
time="2022-07-21T14:23:06Z" level=info msg=started context=watch resource=daemonsets
time="2022-07-21T14:23:06Z" level=info msg=started context=watch resource=cronjobs
E0721 14:23:06.757592 1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.16.10/tools/cache/reflector.go:96: Failed to list *v1.StatefulSet: Get "https://1.2.3.4:443/apis/apps/v1/statefulsets?limit=500&resourceVersion=0": dial tcp 1.2.3.4:443: connect: connection refused
E0721 14:23:06.757648 1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.16.10/tools/cache/reflector.go:96: Failed to list *v1.Deployment: Get "https://1.2.3.4:443/apis/apps/v1/deployments?limit=500&resourceVersion=0": dial tcp 1.2.3.4:443: connect: connection refused
E0721 14:23:06.757671 1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.16.10/tools/cache/reflector.go:96: Failed to list *v1.DaemonSet: Get "https://1.2.3.4:443/apis/apps/v1/daemonsets?limit=500&resourceVersion=0": dial tcp 1.2.3.4:443: connect: connection refused
E0721 14:23:06.757697 1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.16.10/tools/cache/reflector.go:96: Failed to list *v1beta1.CronJob: Get "https://1.2.3.4:443/apis/batch/v1beta1/cronjobs?limit=500&resourceVersion=0": dial tcp 1.2.3.4:443: connect: connection refused
time="2022-07-21T14:23:08Z" level=debug msg="added deployment app1" context=translator
time="2022-07-21T14:23:08Z" level=debug msg="added deployment keel" context=translator
time="2022-07-21T14:23:08Z" level=debug msg="added deployment app2" context=translator
time="2022-07-21T14:23:08Z" level=debug msg="added deployment app3" context=translator
time="2022-07-21T14:23:09Z" level=debug msg="updated deployment keel" context=translator
time="2022-07-21T14:23:09Z" level=debug msg="extension.credentialshelper: credentials not found" error="no secrets were specified" helper=secrets tracked_image="namespace:mynamespace,image:myregistry/app1:1.0.29,provider:kubernetes,trigger:poll,sched:@every 10s,secrets:[]"
time="2022-07-21T14:23:09Z" level=debug msg="extension.credentialshelper: helper doesn't support this registry" error="unsupported registry" helper=aws tracked_image="namespace:mynamespace,image:myregistry/app1:1.0.29,provider:kubernetes,trigger:poll,sched:@every 10s,secrets:[]"
time="2022-07-21T14:23:09Z" level=debug msg="extension.credentialshelper: credentials helper not found" tracked_image="namespace:mynamespace,image:myregistry/app1:1.0.29,provider:kubernetes,trigger:poll,sched:@every 10s,secrets:[]"
time="2022-07-21T14:23:09Z" level=debug msg="registry.manifest.head url=https://myregistry/v2/app1/manifests/1.0.29 repository=app1 reference=1.0.29"
time="2022-07-21T14:23:10Z" level=error msg="trigger.poll.RepositoryWatcher.addJob: failed to get image digest" error="Get \"https://myregistry/v2/app1/manifests/1.0.29\": http: non-successful response (status=401 body=\"{\\n \\\"errors\\\" : [ {\\n \\\"status\\\" : 401,\\n \\\"message\\\" : \\\"Authentication is required\\\"\\n } ]\\n}\")" image="app1:1.0.29" password= username=
time="2022-07-21T14:23:10Z" level=error msg="trigger.poll.RepositoryWatcher.Watch: failed to add image watch job" error="Get \"https://myregistry/v2/app1/manifests/1.0.29\": http: non-successful response (status=401 body=\"{\\n \\\"errors\\\" : [ {\\n \\\"status\\\" : 401,\\n \\\"message\\\" : \\\"Authentication is required\\\"\\n } ]\\n}\")" image="namespace:mynamespace,image:myregistry/app1:1.0.29,provider:kubernetes,trigger:poll,sched:@every 10s,secrets:[]"

```
