### ISSUE TITLE
Deployment will not be updated

### ISSUE THREAD

**Issue by H4CK3R-01** [keel-hq/keel#712]
Hi,
My deployment config contains this code:
```
metadata:
  annotations:
    keel.sh/approvals: "1"
    keel.sh/policy: "all"
    keel.sh/pollSchedule: "@daily"
    keel.sh/trigger: "poll"
    keel.sh/match-tag: "true"
``` 
In keel's dashboard I see the new image version and if I approve it from there keel is logging it:
```
time="2023-03-30T06:18:41Z" level=info msg="approvals.manager: approved" identifier="deployment/<redacted>/<redacted>:latest"
```
But the deployment is not updated. 

What am I doing wrong?
Can it be a problem that I am using the latest image tag?
