### ISSUE TITLE
Helm chart: Ingress not working with release name

### ISSUE THREAD

**Issue by clemenschuaccso** [keel-hq/keel#743]
In the file: https://github.com/keel-hq/keel/blob/master/chart/keel/templates/ingress.yaml
With a release named sandbox this will result to the following objects:
Ingress: sandbox-keel
Service: keel
But the Ingress is pointing to the service sandbox-keel which obviously does not exist.

service/keel manifest:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: keel
    argocd.argoproj.io/instance: sandbox-keel
    chart: keel-1.0.2
    heritage: Helm
    release: sandbox-keel
  name: keel
  namespace: platform
spec:
  ports:
    - name: keel
      port: 9300
      protocol: TCP
      targetPort: 9300
  selector:
    app: keel
  sessionAffinity: None
  type: ClusterIP

```

ingress/sandbox-keel manifest:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/instance: sandbox-keel
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keel
    argocd.argoproj.io/instance: sandbox-keel
    helm.sh/chart: keel-1.0.2
  name: sandbox-keel
  namespace: platform
spec:
  rules:
    - host: SOME_HOSTNAME
      http:
        paths:
          - backend:
              service:
                name: sandbox-keel
                port:
                  name: keel
            path: /
            pathType: Prefix
 
```

Current workaround: set the value `nameOverride`to sandbox-keel.
Possible fix: In Service manifest use fullname for name.
