### ISSUE TITLE
Keel SMTP notification error

### ISSUE THREAD

**Issue by EmilyGrant00** [keel-hq/keel#762]
I am trying to run keel with mail notification configured. Right now, my configuration for notification looks like this:

```
mail:
  enabled: true
  from: "abc@abcd.com"
  to: "xyz@abdc.com"
  smtp:
    server: "smtp.office365.com"
    port:  587
    user: "abc@abcd.com"
    pass: "my_password"
```

Currently when I run keel with this config I get the error:

`
level=error msg="extension.notification.mail: failed to send notification" error="504 5.7.4 Unrecognized authentication type [... .CANPRD01.PROD.OUTLOOK.COM ... ]"
`

Using port 25 for smtp as shown in the docs gives this error instead:

`
level=error msg="extension.notification.mail: failed to send notification" error="dial tcp 40.99.xxx.xx:xx: connect: connection timed out"
`

Seems like it might be outdated? But any help would be appreciated,
Thanks!
