### ISSUE TITLE
Question - How to customise notification messages?

### ISSUE THREAD

**Issue by maoo** [keel-hq/keel#807]
I'm using keel along with Slack notifications, which works quite well (see configurations below), but we'd like to customize the notification message; right now we have:

```
deployment update
Successfully updated deployment <my prj>/<my image>:<my old tag>-> <my new tag>([registry.gitlab.com/<my group>/<my prj>/<my image>:<my new tag>](http://registry.gitlab.com/<my group>/<my prj>/<my image>:<my new tag>)).
```

I've added a `keel.sh/releaseNotes` annotation that allows me to add content, but it's not enough, as we'd like to add what matters most to us at the beginning of the message. Also, the link to the image - `http://registry.gitlab.com/<my group>/<my prj>/<my image>:<my new tag>` - is wrong, it should be `https://gitlab.com/<my group>/<my prj>/container_registry/<my gitlab image ID>` (or simply `https://gitlab.com/<my group>/<my prj>/container_registry` - if the gitlab  image ID is not available)

Is there a helm configuration or an annotation that allows me to override message templates? Any help that you can provide would be greatly appreciated, thank you!

My configurations follow below...

---

Helm chart config:
```
helmProvider:
  enabled: false
keel:
  policy: force
slack:
  enabled: true
  botName: "<my slack bot name>"
  token: "<my slack token>"
  channel: "<my slack channel>"
```

Deployment:
```
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll      
    keel.sh/pollSchedule: "@every 1m"
    keel.sh/releaseNotes: "Environment: {{ $.Values.environment}}"
```
